// 喵喵答疑官（v2）：纯前端、零依赖的检索式教学助手。
// 两部分知识库：
//   1) DICTIONARY（字典词条）：人工写的"是什么/怎么用/搭配/场景/怎么和别的拼"，越补越全；
//   2) ATOMIC_DIVES（124 篇宝宝级深讲）：命中后作为补充例子。
// 不做自由生成，不瞎编。
import { ATOMIC_DIVES } from '../data/atomicDives';
import type { ILessonDeepDive } from '../data/types';

// ---------- 字典词条 ----------
export interface DictEntry {
  id: string;
  title: string;
  aliases: string[]; // 同义词/关键词，用来命中
  meaning: string; // 是什么
  fixedUsage: string; // 固定写法 / 语法骨架
  variants: string; // 哪些部分可变、能填什么
  patterns: { name: string; code: string; note: string }[]; // 常见搭配
  combos: string; // 怎么和别的知识拼起来用
  scenarios: string[]; // 在哪些项目/竞赛/工作场景会用到
  pitfalls: string; // 新手最容易踩的坑
}

export const DICTIONARY: DictEntry[] = [
  {
    id: 'd-var',
    title: '变量与赋值（=）',
    aliases: ['变量', '赋值', '=', '等号', '变量名', '存值', '命名', 'a =', '把值存起来'],
    meaning: '变量就是"给一块数据起个名字"。= 的意思是"把右边算出来的值，贴到左边这个名字上"，不是数学里的"等于"。',
    fixedUsage: '名字 = 值        # 右边先算出来，左边起个名',
    variants: '左边起什么名、右边放什么值都可变；= 这个符号永远表示"赋值"。名字只能用字母/数字/下划线，不能数字开头，不能用关键字。',
    patterns: [
      { name: '基本赋值', code: 'price = 99.5\nname = "小明"\ncount = 0', note: '一行一个，先右后左。' },
      { name: '连续赋值', code: 'a = b = 0      # a 和 b 都等于 0', note: '从右往左贴。' },
      { name: '解包赋值', code: 'x, y = 1, 2     # x=1, y=2\nx, y = y, x     # 一行交换', note: 'Python 特有的好用法。' },
      { name: '自增', code: 'count = count + 1\ncount += 1        # 简写', note: '+= 就是"在原来基础上加"。' },
    ],
    combos: '和输入一起用：name = input("名字：")；和循环一起用：sum = 0 然后 for 里 sum += x；和函数一起用：把算出来的结果 return 出来再赋值。',
    scenarios: ['p19 个人作品集', 'p2 用户行为分析', '几乎每个 Python 项目第一行都在用'],
    pitfalls: '把 = 当成"等于"。判断相等要用 ==（两个等号）。a = b 是把 b 当前的值抄一份给 a，之后 b 变了 a 不会跟着变。',
  },
  {
    id: 'd-eq',
    title: '== 与 =（相等 vs 赋值）',
    aliases: ['==', '等于', '相等', '双等号', '判断相等', 'if ==', '=和==区别'],
    meaning: '= 是"把右边的值贴到左边名字上"（赋值）；== 是"判断两边是不是同一个值"，结果是 True 或 False。',
    fixedUsage: 'if a == b:    # 问：a 和 b 相等吗？\nif a != b:    # 不相等吗？',
    variants: '中间可以换 >、<、>=、<=、!=；两边放任何能比的值。',
    patterns: [
      { name: '判断相等', code: 'age = 18\nif age == 18:\n    print("成年")', note: '两个等号才是判断。' },
      { name: '在列表里', code: 'if name in ["小明", "小红"]:\n    print("在名单里")', note: '判断"在不在"用 in，不是 ==。' },
    ],
    combos: '和 if/while 一起用做分支；和 input() 一起做菜单选择；和函数返回值一起 if result == "ok"。',
    scenarios: ['p14 校园二手的表单校验', 'p2 漏斗步骤判断', '竞赛里条件判断'],
    pitfalls: '最常见的 bug：if a = b（一个等号）在 Python 里是赋值，会报错；写条件一定要两个等号 ==。',
  },
  {
    id: 'd-def',
    title: '函数（def）',
    aliases: ['def', '函数', '方法', '定义函数', '参数', '返回', 'return', '调用函数'],
    meaning: '函数就是"打包一段会重复用的代码"，起个名字，下次用名字就能调，不用重写。',
    fixedUsage: 'def 名字(参数1, 参数2):\n    做的事\n    return 结果',
    variants: '函数名、参数个数、里面做什么都可变；return 可省（不 return 就返回 None）。',
    patterns: [
      { name: '无参数', code: 'def hello():\n    print("你好")\nhello()', note: 'hello() 就是调用。' },
      { name: '带参数', code: 'def add(a, b):\n    return a + b\nprint(add(1, 2))   # 3', note: 'a、b 是占位，调用时传真实值。' },
      { name: '带默认值', code: 'def greet(name, greeting="你好"):\n    print(greeting, name)\ngreet("小明")            # 用默认\ngreet("小红", "嗨")      # 覆盖默认', note: '= 在参数里叫默认值。' },
      { name: '类型标注（企业写法）', code: 'def average(scores: list[float]) -> float:\n    return sum(scores) / len(scores)', note: '告诉读者"传一个小数列表，返回一个小数"，不强制。' },
    ],
    combos: '函数里可以再调别的函数；可以把函数当参数传；和 if 一起：def 里根据参数走不同分支；和循环一起：def 里批量处理数据。',
    scenarios: ['p2 行为分析：把"算转化率"包成函数复用', 'p3 RAG：把"检索→生成"包成 ask(question)', '竞赛：每个小步骤写成函数方便测'],
    pitfalls: '忘了冒号 :；函数体要缩进 4 格；调用时传的参数个数要和定义对上；return 不是 print——print 只显示，return 是把结果交出去。',
  },
  {
    id: 'd-main',
    title: "if __name__ == '__main__'",
    aliases: ['__main__', '__name__', '__name__ ==', 'main', '入口', 'python report.py', '被 import'],
    meaning: '这是 Python 的"程序入口"惯用法。每个 .py 文件都可以直接运行，也可以被别的文件 import。这行的意思是："只有当这个文件是被直接运行的，才执行下面的测试代码；如果它是被别人 import 的，就不要自动跑。"',
    fixedUsage: "def run():\n    print('跑分析')\n\nif __name__ == '__main__':\n    run()",
    variants: 'if 下面调用哪个函数、做什么都可变；这一行的字面量一般照抄。',
    patterns: [
      { name: '直接运行', code: '# 命令行：python report.py\n# 此时 __name__ 等于 "__main__"\n# → 执行 run()', note: '你自己跑这个文件时生效。' },
      { name: '被 import', code: '# 另一个文件：from report import run\n# 此时 __name__ 等于 "report"\n# → if 不成立，run() 不会自动执行', note: '别人用你的函数时，不会把测试代码也跑一遍。' },
    ],
    combos: '和函数配合：把主要逻辑写成 run()，在 if 里调用；和命令行参数配合：if 里读 sys.argv；和单元测试配合：测试文件 import 你的模块而不触发主逻辑。',
    scenarios: ['p3 RAG 项目的 main.py 入口', 'p10 PyTorch 训练脚本', '竞赛提交的 python 脚本'],
    pitfalls: "把 __name__ 和 '__main__' 两边都忘了两个下划线；冒号不能少；if 下面的代码要缩进。不写这行也能跑，但被 import 时会自动执行你的测试代码，容易出 bug。",
  },
  {
    id: 'd-if',
    title: '条件判断 if / elif / else',
    aliases: ['if', 'elif', 'else', '条件', '分支', '判断', '否则'],
    meaning: '让程序"看情况做事"：满足条件走 A，不满足走 B。',
    fixedUsage: 'if 条件:\n    条件成立时做的事\nelif 另一个条件:\n    ...\nelse:\n    都不成立时做的事',
    variants: '条件写什么、每个分支做什么都可变；elif 和 else 可省。',
    patterns: [
      { name: '二选一', code: 'age = 20\nif age >= 18:\n    print("成年")\nelse:\n    print("未成年")', note: '' },
      { name: '多选一', code: 'score = 85\nif score >= 90:\n    g = "A"\nelif score >= 80:\n    g = "B"\nelse:\n    g = "C"', note: '从上往下，命中第一个就停。' },
      { name: '组合条件', code: 'if age >= 18 and vip:\n    print("可进")\nif not banned:\n    print("正常")', note: 'and/or/not。' },
    ],
    combos: '和 input 做菜单；和列表循环一起：for 里 if 过滤；和函数一起：函数里根据参数走分支返回不同结果。',
    scenarios: ['p14 表单校验（空标题就拦）', 'p28 AB 实验分组', '竞赛里条件筛选'],
    pitfalls: '每个 if/elif/else 后面的冒号不能少；分支内必须缩进；条件不用小括号（和 C/Java 不同）。',
  },
  {
    id: 'd-for',
    title: '循环 for in',
    aliases: ['for', '循环', '遍历', 'for in', '逐个', '重复', 'range'],
    meaning: '把一个列表/一串东西里的每个元素"挨个拿出来"处理一遍。',
    fixedUsage: 'for 变量 in 一串东西:\n    对每个东西做的事',
    variants: '变量叫什么、遍历什么、里面做什么都可变。',
    patterns: [
      { name: '遍历列表', code: 'for name in ["小明", "小红"]:\n    print(name)', note: 'name 依次是每一个。' },
      { name: 'range 数数字', code: 'for i in range(3):\n    print(i)        # 0 1 2', note: 'range(n) 从 0 到 n-1。' },
      { name: '累加器', code: 'total = 0\nfor x in [1, 2, 3]:\n    total += x\nprint(total)      # 6', note: '先在外面置 0，再在循环里加。' },
      { name: '带下标', code: 'for i, name in enumerate(["a", "b"]):\n    print(i, name)', note: 'i 是位置，name 是元素。' },
    ],
    combos: '和 if 一起做过滤；和列表推导式一起写一行；和函数一起：把每个元素传给函数。',
    scenarios: ['p2 遍历每个用户算留存', 'p7 遍历每周数据出报表', '竞赛：遍历所有数据点'],
    pitfalls: '循环变量名会"残留"在外面（最后一个值）；range(3) 不是 1,2,3 而是 0,1,2；别在遍历列表时同时改这个列表。',
  },
  {
    id: 'd-list',
    title: '列表 list',
    aliases: ['list', '数组', '列表', '[]', 'append', '切片', '索引', '下标'],
    meaning: '列表就是"按顺序排好的一排格子"，每个格子有编号（从 0 开始），可以放任何东西。',
    fixedUsage: '名字 = [元素1, 元素2, ...]\n名字[0]      # 第 1 个\n名字.append(新)',
    variants: '里面放什么、放几个都可变；用 [] 写，用 0 开始的下标取。',
    patterns: [
      { name: '建与取', code: 'nums = [10, 20, 30]\nprint(nums[0])    # 10\nprint(nums[-1])   # 30（倒数）', note: '0 开始，-1 是最后。' },
      { name: '增删', code: 'nums.append(40)   # 末尾加\nnums.pop()         # 删末尾\nnums[0] = 99       # 改', note: '' },
      { name: '切片', code: 'nums[0:2]   # 取前 2 个\nnums[1:]    # 从第 2 个到末尾', note: '左含右不含。' },
      { name: '遍历', code: 'for x in nums:\n    print(x)', note: '' },
    ],
    combos: '和 for 一起遍历；和 if 一起过滤出新列表；和函数一起：return 一个列表；和 dict 一起：列表里每个元素是一个字典。',
    scenarios: ['p2 把每天的指标存成列表', 'p12 推荐：候选物品是一个列表', 'p10 数据集：图片路径列表'],
    pitfalls: '下标越界（空列表取 [0] 会报错）；nums[-1] 在空列表也会报错；append 是在原列表上加，不会返回新列表。',
  },
  {
    id: 'd-dict',
    title: '字典 dict',
    aliases: ['dict', '字典', '{}', '键值', 'key', 'value', '键值对', 'map'],
    meaning: '字典就是"带名字的格子"：用一个 key 直接找对应的 value，不用数下标。像查字典。',
    fixedUsage: '名字 = {key1: 值1, key2: 值2}\n名字[key1]       # 取值\n名字[key3] = 值3  # 加/改',
    variants: 'key 一般用字符串；value 可以是任何东西（数字、列表、甚至另一个字典）。',
    patterns: [
      { name: '建与取', code: 'user = {"name": "小明", "age": 18}\nprint(user["name"])   # 小明', note: '用 key 取。' },
      { name: '安全取值', code: 'user.get("phone", "未填")', note: '不存在不报错，给默认值。' },
      { name: '遍历', code: 'for k, v in user.items():\n    print(k, v)', note: '同时拿 key 和 value。' },
      { name: '嵌套', code: 'order = {"user": {"name": "小明"}, "items": ["书", "笔"]}', note: '真实数据经常长这样。' },
    ],
    combos: '从 API 拿到的 JSON 就是字典/列表的嵌套；和列表一起：一批用户 = [字典, 字典, ...]；和函数一起：把多个参数打包成一个 dict 传。',
    scenarios: ['p6 文章评论是 JSON dict', 'p11 支付对账：每笔流水是 dict', 'p3 RAG：每条检索结果是 dict'],
    pitfalls: '取不存在的 key 用 [] 会 KeyError，用 .get() 才安全；key 重复后面会覆盖前面；缩进和冒号别漏。',
  },
  {
    id: 'd-input',
    title: 'input() 与 print()',
    aliases: ['input', 'print', '输入', '输出', '打印', '控制台', '命令行交互'],
    meaning: 'input() 是"让用户在键盘敲点东西，程序接住"；print() 是"在屏幕上显示一行字"。',
    fixedUsage: 'name = input("提示语：")   # 拿到的永远是字符串\nprint(name)',
    variants: '提示语写什么、显示什么都可变。',
    patterns: [
      { name: '读文字', code: 'name = input("你叫什么？")\nprint("你好", name)', note: 'input 出来都是字符串。' },
      { name: '读数字要转', code: 'age = int(input("年龄："))\nif age >= 18: ...', note: 'int() 把字符串转成整数。' },
      { name: 'f-string 拼接', code: 'print(f"你好 {name}，今年 {age} 岁")', note: 'f 开头，{} 里放变量。' },
    ],
    combos: '和 if 一起做菜单；和 while 一起做循环问答；在命令行工具脚本里当人机接口。',
    scenarios: ['p19 本地小工具', '竞赛命令行题', '自己写的调试脚本'],
    pitfalls: 'input() 拿到的永远是字符串，要做计算必须 int()/float() 转；input 在非交互环境（被 import）会卡。',
  },
  {
    id: 'd-error',
    title: '报错与调试（看懂红字）',
    aliases: ['报错', 'error', 'traceback', 'bug', '不明白报错', '红色错误', 'KeyError', 'NameError'],
    meaning: '红字最后一行才是真正的错误原因，上面是"代码走到哪儿了"。从下往上读：先看最后一行是什么错，再往上找自己写的哪一行。',
    fixedUsage: '# 常见：\n# NameError     名字没定义（拼错/没赋值）\n# TypeError     类型不对（字符串当数字加）\n# KeyError      字典里没这个 key\n# IndexError    列表下标越界',
    variants: '根据错误名去搜/改对应问题。',
    patterns: [
      { name: '读报错', code: 'print(usre)\n# NameError: name \'usre\' is not defined\n# 你想写 user，拼错了', note: '最后一行：什么错+什么名字。' },
      { name: '先打出来看看', code: 'print(type(x))\nprint(x)\n# 在怀疑的地方加打印', note: '不知道变量是什么就先 print 它。' },
      { name: '小步验证', code: '把出问题的那行，拆成几行，一行行试', note: '别一次写十行再跑。' },
    ],
    combos: '和 print 一起调试；和函数一起：把出问题的小段单独跑；和 try/except 一起：对可预见的错兜底。',
    scenarios: ['所有项目都在调 bug', '竞赛提交前自查', '面试常考"怎么定位 bug"'],
    pitfalls: '不要从头到尾读红字；不要看到红字就重写整个程序——先定位是哪一行、什么错。',
  },
  {
    id: 'd-str',
    title: '字符串操作（split / join / f-string）',
    aliases: ['字符串', 'split', 'join', 'f-string', '格式化', '切片字符串', 'replace', 'strip', 'in'],
    meaning: '字符串就是一段文本。Python 里字符串是"不可变"的——每次操作都返回新字符串，原串不变。',
    fixedUsage: 's = "hello world"\ns.split(" ")     # 切开成列表\n" ".join(lst)      # 列表拼回字符串\nf"{变量}"          # 插值',
    variants: '分隔符写什么、变量放什么都可变；字符串用引号包起来（单/双都行，不能混用）。',
    patterns: [
      { name: '拆分', code: 'line = "2026-09-20,小明,99"\nparts = line.split(",")', note: 'CSV/日志行常用。' },
      { name: '拼接', code: '"-".join(["2026","09","20"])', note: '别用 + 拼大字符串。' },
      { name: '插值', code: 'name = "小明"\nprint(f"你好 {name}")', note: 'f 开头，{} 里能算。' },
      { name: '常用方法', code: 's.strip()\ns.replace("a","b")\ns.upper() / s.lower()\n"小明" in name', note: '都返回新串。' },
      { name: '切片', code: 's[0:3]   # 前 3 个\ns[-4:]   # 后 4 个', note: '和列表一样。' },
    ],
    combos: '和 split 读 CSV；和 dict 一起把字段拼成 SQL；和函数一起把结果格式化输出。',
    scenarios: ['p2 清洗埋点日志', 'p7 报表拼接', '竞赛：处理输入输出格式'],
    pitfalls: '字符串不可变：s.replace(...) 不会改 s，要重新赋值；split 不出结果时检查分隔符。',
  },
  {
    id: 'd-while',
    title: 'while 循环与 break/continue',
    aliases: ['while', 'break', 'continue', '死循环', '一直循环', '跳出', '跳过'],
    meaning: 'while 是"只要条件成立就一直做"。break 立刻跳出整个循环；continue 跳过这一轮进下一轮。',
    fixedUsage: 'while 条件:\n    做事\n    if 某情况: break',
    variants: '条件写什么、里面做什么都可变。',
    patterns: [
      { name: '计数循环', code: 'n = 3\nwhile n > 0:\n    print(n)\n    n -= 1', note: '别忘了改条件。' },
      { name: '菜单循环', code: 'while True:\n    cmd = input("> ")\n    if cmd == "q": break', note: '一直问直到 q。' },
      { name: '跳过本轮', code: 'for x in range(5):\n    if x % 2 == 0: continue\n    print(x)', note: '只打印奇数。' },
    ],
    combos: '和 input 做命令行交互；和 try/except 做重试；和 break 退出菜单。',
    scenarios: ['p15 自动化脚本重试', '竞赛：读输入直到结束', '自己写的小工具'],
    pitfalls: '忘记改循环变量导致死循环；while True 必须有 break 出口。',
  },
  {
    id: 'd-try',
    title: '异常处理 try / except',
    aliases: ['try', 'except', '异常', '报错处理', '容错', 'try except', 'finally'],
    meaning: 'try 是"试试这段代码"；出错了不崩，跳到 except 里处理。用于"预料到可能出错"的地方。',
    fixedUsage: 'try:\n    可能出错的代码\nexcept 错误类型:\n    出问题时怎么办',
    variants: '监控什么错误、出错后怎么处理都可变；except 后不写类型会抓所有错（不推荐）。',
    patterns: [
      { name: '安全转换', code: 'try:\n    age = int(input("年龄"))\nexcept ValueError:\n    age = 0', note: '用户输错也不崩。' },
      { name: '多分支', code: 'except FileNotFoundError:\n    print("文件不存在")\nexcept Exception as e:\n    print("别的错", e)', note: '越具体越靠前。' },
      { name: 'finally', code: 'finally:\n    f.close()', note: '不管成不成功都执行。' },
    ],
    combos: '和文件读写防文件不存在；和网络请求防超时；和 while 做重试。',
    scenarios: ['p3 RAG 调 API 失败兜底', 'p15 自动化测试', '所有对外调用'],
    pitfalls: '别用裸 except: 抓所有错；别为了不报错就吞错，至少 print。',
  },
  {
    id: 'd-file',
    title: '文件读写（with open）',
    aliases: ['文件', 'open', 'read', 'write', 'csv', '读文件', '写文件', 'with open'],
    meaning: 'open 打开文件，with 保证用完自动关。读是 r，写是 w（覆盖），追加是 a。',
    fixedUsage: 'with open("a.txt", "r", encoding="utf-8") as f:\n    text = f.read()',
    variants: '文件名、模式、编码可变；编码一定要写 utf-8 否则中文乱码。',
    patterns: [
      { name: '读全文', code: 'with open("a.txt", encoding="utf-8") as f:\n    text = f.read()', note: '' },
      { name: '逐行读', code: 'with open("a.txt", encoding="utf-8") as f:\n    for line in f:\n        print(line.strip())', note: '大文件别 read()。' },
      { name: '写文件', code: 'with open("out.txt","w",encoding="utf-8") as f:\n    f.write("第一行\\n")', note: 'w 会覆盖。' },
      { name: '追加', code: 'with open("log.txt","a",encoding="utf-8") as f:\n    f.write("又一行\\n")', note: '' },
    ],
    combos: '和 split 解析日志；和 csv 模块读表格；和 json 存配置。',
    scenarios: ['p2 读埋点文件', 'p7 出报表写文件', '竞赛：读写输入输出'],
    pitfalls: '忘了 encoding="utf-8" 中文乱码；w 模式直接覆盖；with 之外不能用 f。',
  },
  {
    id: 'd-import',
    title: '模块与 import',
    aliases: ['import', '模块', '包', 'from import', '库', 'install', 'pip'],
    meaning: '把别人写好的代码拿来用。import 模块；from 模块 import 具体东西；自己写的 .py 也是模块。',
    fixedUsage: 'import 模块名\nfrom 模块名 import 名字\nimport 模块名 as 别名',
    variants: '导入什么、起什么别名可变。',
    patterns: [
      { name: '标准库', code: 'import os\nimport json\nfrom pathlib import Path', note: 'Python 自带。' },
      { name: '第三方', code: '# 先装：pip install requests\nimport requests', note: '' },
      { name: '起别名', code: 'import pandas as pd\nimport numpy as np', note: '社区惯例。' },
      { name: '自己的模块', code: '# 同目录 report.py\ndef run(): ...\n# 另一个文件：\nfrom report import run', note: '被 import 不自动跑。' },
    ],
    combos: '和 if __name__ 配合；和函数组织代码；项目大了按目录拆模块。',
    scenarios: ['p3 import 各种 AI 库', 'p10 import torch', '几乎每个项目开头'],
    pitfalls: '装了没 import 不行；import 了没装报 ModuleNotFoundError；别把文件命名成 requests.py。',
  },
  {
    id: 'd-comp',
    title: '列表/字典推导式',
    aliases: ['推导式', '列表推导', 'comprehension', '[x for', '[i for', '一行生成列表'],
    meaning: '用一行 for 把一个列表加工成新列表，Python 最常用的简洁写法。',
    fixedUsage: '[表达式 for 元素 in 旧列表 if 条件]',
    variants: '表达式、元素、条件都可变；不加 if 就是全部加工。',
    patterns: [
      { name: '加工', code: '[x*2 for x in [1,2,3]]   # [2,4,6]', note: '' },
      { name: '过滤', code: '[x for x in [1,2,3,4] if x%2==0]', note: '只要偶数。' },
      { name: '提取字段', code: '[u["name"] for u in users]', note: '从字典列表抽名字。' },
      { name: '字典推导', code: '{x: x*2 for x in range(3)}', note: '' },
    ],
    combos: '和 dict 处理 API 数据；和函数：[f(x) for x in data]；替代 for+append。',
    scenarios: ['p2 数据清洗', 'p12 特征工程', '竞赛：简洁生成答案'],
    pitfalls: '太复杂就别硬写一行，可读性比简洁重要。',
  },
  {
    id: 'd-class',
    title: '类 class（面向对象入门）',
    aliases: ['class', '类', '对象', '面向对象', 'self', '__init__', '实例'],
    meaning: '类是模板，对象是按模板造出来的具体东西。把数据和操作数据的函数打包在一起。',
    fixedUsage: 'class 名字:\n    def __init__(self, 参数):\n        self.属性 = 参数',
    variants: '类名、属性、方法都可变；self 是固定写法。',
    patterns: [
      { name: '最小类', code: 'class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(self.name, ": 汪")\n\nDog("旺财").bark()', note: '__init__ 造对象时自动跑。' },
    ],
    combos: '和数据结构：一个用户一个对象；和库：继承基类；项目大了用类组织。',
    scenarios: ['p6 文章类/评论类', 'p10 自定义 Dataset', '读框架源码到处是 class'],
    pitfalls: '方法第一个参数永远是 self；忘写 self. 属性就丢了；函数够用就别硬上类。',
  },
  {
    id: 'd-args',
    title: '*args 与 **kwargs',
    aliases: ['args', 'kwargs', '*args', '**kwargs', '可变参数', '关键字参数', '默认参数'],
    meaning: '让函数接收个数不固定的参数。*args 收多余位置参数（元组）；**kwargs 收多余命名参数（字典）。',
    fixedUsage: 'def f(*args, **kwargs):\n    print(args)     # 元组\n    print(kwargs)   # 字典',
    variants: '名字叫 args/kwargs 是惯例，* 和 ** 才是关键。',
    patterns: [
      { name: '任意多参数', code: 'def total(*nums):\n    return sum(nums)\ntotal(1,2,3)', note: '' },
      { name: '命名参数', code: 'def config(**kv):\n    for k,v in kv.items(): print(k,v)\nconfig(host="a", port=80)', note: '' },
      { name: '解包传入', code: 'a = [1,2,3]\ntotal(*a)', note: '等价 total(1,2,3)。' },
    ],
    combos: '写装饰器/中间件必用；调框架函数透传参数；写工具函数做通用。',
    scenarios: ['p3 FastAPI 路由函数', 'p13 CI 脚本', '读库源码到处是'],
    pitfalls: '*args 是元组不能按 key 取；别为了显得高级乱用。',
  },
  {
    id: 'd-lambda',
    title: 'lambda 匿名函数',
    aliases: ['lambda', '匿名函数', '一行函数', 'map', 'filter'],
    meaning: '一行小函数，没名字，通常传给需要函数当参数的地方（排序、map）。',
    fixedUsage: 'lambda 参数: 表达式',
    variants: '参数、返回什么都可变；只能写一个表达式。',
    patterns: [
      { name: '排序用', code: 'users.sort(key=lambda u: u["age"])', note: '最常见。' },
      { name: 'map 加工', code: 'list(map(lambda x: x*2, [1,2,3]))', note: '更推荐列表推导式。' },
    ],
    combos: '和 sort/sorted 的 key 搭配；和 pandas 的 apply 搭配；太复杂就用 def。',
    scenarios: ['p12 推荐排序', 'p2 排序漏斗', '读 pandas 代码'],
    pitfalls: 'lambda 里不能写多行逻辑；简单用一下就好。',
  },
  {
    id: 'd-json',
    title: 'JSON 与字典互转',
    aliases: ['json', 'JSON', '序列化', 'loads', 'dumps', 'API 返回', '配置文件'],
    meaning: 'JSON 是跨语言文本格式（长得像字典）。API 收发、存配置都用它。字典 ⇄ JSON 字符串靠 json 模块。',
    fixedUsage: 'import json\n文本 = json.dumps(字典)\n字典 = json.loads(文本)',
    variants: '要转的内容、存哪都可变。',
    patterns: [
      { name: '转文本', code: 'json.dumps(d, ensure_ascii=False)', note: '中文不转义。' },
      { name: '转回', code: 'd = json.loads(\'{"name":"小明"}\')', note: '' },
      { name: '读 JSON 文件', code: 'with open("c.json", encoding="utf-8") as f:\n    cfg = json.load(f)', note: '' },
      { name: '写 JSON 文件', code: 'json.dump(cfg, f, ensure_ascii=False, indent=2)', note: '' },
    ],
    combos: '和 requests：r.json() 直接得字典；和文件读写存配置；和 dict 取字段。',
    scenarios: ['p3 解析大模型返回', 'p6 存文章数据', '几乎所有后端项目'],
    pitfalls: 'JSON 的 key 必须双引号；忘 ensure_ascii=False 中文变 \\uXXXX。',
  },
  {
    id: 'd-num',
    title: '数字与运算（// % 与类型转换）',
    aliases: ['数字', '运算', 'int', 'float', '除法', '取余', '取整', '//', '%', '加减乘除', '类型转换'],
    meaning: 'Python 里 / 是真除法（得小数）；// 是整除（丢掉小数）；% 是取余数。int() 转整数，float() 转小数。',
    fixedUsage: '7 / 2   # 3.5\n7 // 2  # 3\n7 % 2   # 1\nint("99")   # 99\nfloat("3.14")',
    variants: '操作数是什么都可变；运算符固定。',
    patterns: [
      { name: '整除与取余', code: '9 / 4   # 2.25\n9 // 4  # 2\n9 % 4   # 1', note: '% 常用于判断奇偶。' },
      { name: '判断奇偶', code: 'if x % 2 == 0:\n    print("偶数")', note: '' },
      { name: '进位与位数', code: 'total = 125\n分 = total // 100   # 1\n余 = total % 100     # 25', note: '' },
      { name: '类型转换', code: 'int("18")      # 字符串转整数\nstr(18)        # 数字转字符串\nfloat("1.5")', note: 'input 拿到的是字符串，要算就转。' },
    ],
    combos: '和 for 一起做累加；和 if 做奇偶/范围判断；和 datetime 做时间计算。',
    scenarios: ['竞赛：数学题', 'p2 算转化率', '所有数值计算'],
    pitfalls: '整数除整数在 Python 3 里 / 会得小数；% 负数结果可能反直觉；字符串和数字不能直接相加。',
  },
  {
    id: 'd-tuple',
    title: '元组 tuple 与集合 set',
    aliases: ['tuple', '元组', 'set', '集合', '去重', '不可变'],
    meaning: '元组 () 就是"定死的列表"，建好不能改；集合 {} 是"不重复的一堆东西"，自动去重。',
    fixedUsage: 't = (1, 2, 3)\ns = {1, 2, 2, 3}   # {1,2,3}',
    variants: '里面放什么都可变。',
    patterns: [
      { name: '元组', code: 'point = (10, 20)\nx, y = point      # 解包\n# point[0] = 99  # 报错！元组不可改', note: '' },
      { name: '集合去重', code: 'names = ["a","b","a","c"]\nunique = list(set(names))   # ["a","b","c"]', note: '最常用。' },
      { name: '交并差', code: 'a = {1,2,3}; b = {2,3,4}\na & b   # {2,3} 交\na | b   # {1,2,3,4} 并\na - b   # {1} 差', note: '' },
    ],
    combos: '和列表推导式去重；和 dict 一起判断 key 是否存在；函数返回多个值时用元组。',
    scenarios: ['p2 去重用户', 'p12 找共同物品', '竞赛：去重题'],
    pitfalls: 'set 无序不能按下标取；元组里放可变对象（如列表）仍可变；不要把 set 当列表用。',
  },
  {
    id: 'd-datetime',
    title: '时间与日期 datetime',
    aliases: ['datetime', '时间', '日期', 'now', 'strptime', 'strftime', 'timestamp'],
    meaning: 'datetime 模块处理时间：取当前时间、解析字符串、加减天数、格式化显示。',
    fixedUsage: 'from datetime import datetime, timedelta\nnow = datetime.now()\n文本 = now.strftime("%Y-%m-%d")',
    variants: '格式串写什么、加减多少都可变。',
    patterns: [
      { name: '当前时间', code: 'from datetime import datetime\nnow = datetime.now()\nprint(now.year, now.month, now.day)', note: '' },
      { name: '字符串转时间', code: "dt = datetime.strptime('2026-09-20', '%Y-%m-%d')", note: '' },
      { name: '时间转字符串', code: "now.strftime('%Y年%m月%d日')", note: '' },
      { name: '加减天', code: 'from datetime import timedelta\nyesterday = now - timedelta(days=1)\nafter7 = now + timedelta(days=7)', note: '' },
    ],
    combos: '和 SQL 一起按天筛选；和文件读写按日期命名报表；和 pandas 做时间序列。',
    scenarios: ['p2 次留计算', 'p7 按周出报表', 'p17 数仓按天分区'],
    pitfalls: 'strptime 解析和 strftime 输出格式要对应；时区问题项目里先不管；别自己手算月份差。',
  },
  {
    id: 'd-re',
    title: '正则表达式 re',
    aliases: ['re', '正则', 'regex', '匹配', '查找', '替换文本', 'search', 'findall'],
    meaning: '用"通配规则"在一大段文本里找/替换符合模式的内容，比 split/replace 灵活得多。',
    fixedUsage: 'import re\nre.findall(r"\\d+", 文本)   # 找出所有数字',
    variants: '规则串写什么可变。常用：\\d 数字、\\w 字母数字、. 任意、* 0次或多次、+ 1次或多次、[] 任选。',
    patterns: [
      { name: '找所有数字', code: 're.findall(r"\\d+", "订单A123，共2件")   # ["123","2"]', note: '' },
      { name: '替换', code: "re.sub(r'\\s+', ' ', text)   # 多个空格变一个", note: '' },
      { name: '判断是否匹配', code: 'if re.search(r"\\d{11}", text):\n    print("像手机号")', note: '' },
    ],
    combos: '和文件读写清洗日志；和 dict 提取字段；和 pandas 的 str.replace。',
    scenarios: ['p2 清洗埋点', 'p3 文档切分', '竞赛：字符串处理题'],
    pitfalls: '先在小工具里试规则；转义符要写 r"" 原始字符串；别用正则解析 HTML（用专门库）。',
  },
  {
    id: 'd-sort',
    title: '排序 sort / sorted',
    aliases: ['sort', 'sorted', '排序', '升序', '降序', 'key', 'reverse'],
    meaning: 'sorted 返回新排序列表；list.sort() 原地排。用 key 指定按什么排，reverse=True 倒序。',
    fixedUsage: 'sorted(列表, key=函数, reverse=False)',
    variants: 'key 写什么、升序降序可变。',
    patterns: [
      { name: '默认排序', code: 'sorted([3,1,2])   # [1,2,3]', note: '' },
      { name: '按字段排', code: 'users.sort(key=lambda u: u["age"], reverse=True)', note: '年龄从大到小。' },
      { name: '多关键字', code: 'sorted(lst, key=lambda x: (x["city"], -x["age"]))', note: '先按城市，再按年龄倒序。' },
    ],
    combos: '和 lambda 一起；和 dict 列表排 TopN；和排行榜结合。',
    scenarios: ['p12 推荐 TopN', 'p2 排行榜', '竞赛：排序题'],
    pitfalls: 'sort() 返回 None（原地改）；要新列表用 sorted；key 别用复杂函数。',
  },
  {
    id: 'd-pip',
    title: 'pip 与虚拟环境',
    aliases: ['pip', '虚拟环境', 'venv', 'install', 'requirements', '安装库'],
    meaning: 'pip 是装第三方库的命令；venv 是给每个项目单独造一个隔离环境，避免版本冲突。',
    fixedUsage: '# 创建\npython -m venv .venv\n# 激活（Windows）\n.venv\\Scripts\\activate\n# 装库\npip install requests\npip freeze > requirements.txt',
    variants: '库名、版本可变。',
    patterns: [
      { name: '装一个库', code: 'pip install pandas', note: '' },
      { name: '锁定版本', code: 'pip freeze > requirements.txt\n# 别人：pip install -r requirements.txt', note: '' },
      { name: '指定版本', code: 'pip install pandas==2.2', note: '' },
    ],
    combos: '和 import 对应（装了才能 import）；和项目 README 一起写安装步骤。',
    scenarios: ['p3 装 faiss/openai', 'p10 装 torch', '所有项目'],
    pitfalls: '别全局乱装一堆库版本；装完没激活 venv 可能用错环境；requirements.txt 要跟着项目走。',
  },
  {
    id: 'd-pkg',
    title: '自定义模块与包',
    aliases: ['模块', '包', '__init__', '目录结构', 'from x.y import', '组织代码'],
    meaning: '代码多了就按目录拆：一个文件夹是一个包，里面每个 .py 是模块。文件夹要有 `__init__.py`（新版本可空）。',
    fixedUsage: 'project/\n  main.py\n  utils/\n    __init__.py\n    calc.py   # 里面 def add()',
    variants: '怎么拆目录、命名可变。',
    patterns: [
      { name: '导入子模块', code: '# main.py\nfrom utils.calc import add\nadd(1,2)', note: '' },
      { name: '包级导出', code: '# utils/__init__.py\nfrom .calc import add', note: '让外部 from utils import add。' },
    ],
    combos: '和 import 一起；项目大了按功能拆（model/service/util）；和 Git 一起管理。',
    scenarios: ['p6 全栈项目后端组织', 'p3 RAG 项目结构', '真实项目都是这样拆的'],
    pitfalls: '同名文件互相 import 会死循环；相对导入 .calc 和绝对导入别混；__init__.py 别写重活。',
  },
  {
    id: 'd-debug',
    title: '调试思路（print / assert / 小步跑）',
    aliases: ['调试', 'debug', 'print 调试', 'assert', '怎么找 bug', '打断点'],
    meaning: '调试不是乱猜，是"把不知道的东西打出来看"。最常用三招：print 出中间值、assert 定假设、把大段代码拆成小段跑。',
    fixedUsage: 'print("这里 x =", x, type(x))\nassert x > 0, "x 不该是负数"',
    variants: '打什么、假设什么可变。',
    patterns: [
      { name: '打中间值', code: 'result = 你不知道对不对的函数()\nprint(result)\nprint(type(result))', note: '' },
      { name: '定假设', code: 'assert len(data) > 0, "数据是空的！"', note: '不符合立刻报错并提示。' },
      { name: '复现最小例子', code: '把出错的那行单独拎出来，用最小输入跑', note: '' },
    ],
    combos: '和 try/except 配合；和函数一起：把可疑小段单独测试；和 Git 一起：出问题就 git diff 看改了啥。',
    scenarios: ['所有项目', '竞赛调 bug', '面试常考'],
    pitfalls: '别一上来重写整个程序；别用 print 完就忘删（正式代码要清掉）；先复现再修。',
  },
  {
    id: 'd-pandas',
    title: 'pandas 入门（DataFrame）',
    aliases: ['pandas', 'DataFrame', 'df', 'read_csv', '表格', '数据处理', 'dataframe'],
    meaning: 'pandas 是 Python 处理表格数据的事实标准。DataFrame 就是"一张内存里的 Excel 表"。',
    fixedUsage: 'import pandas as pd\ndf = pd.read_csv("data.csv")\ndf.head()',
    variants: '读什么、选哪几列、做什么操作可变。',
    patterns: [
      { name: '读表格', code: 'df = pd.read_csv("data.csv")\ndf.head()       # 前 5 行\ndf.shape       # (行, 列)', note: '' },
      { name: '选列与过滤', code: 'df["name"]\ndf[df["age"] > 18]', note: '' },
      { name: '分组统计', code: 'df.groupby("city")["age"].mean()', note: '按城市算平均年龄。' },
      { name: '加一列', code: 'df["total"] = df["price"] * df["count"]', note: '' },
      { name: '导出', code: 'df.to_csv("out.csv", index=False)', note: '' },
    ],
    combos: '和文件读写读 CSV；和 dict/列表构造 DataFrame；和 matplotlib 出图。',
    scenarios: ['p2 用户行为分析', 'p7 报表自动化', 'p28 AB 实验分析'],
    pitfalls: '链式赋值 SettingWithCopyWarning（用 .loc）；read_csv 中文编码要 encoding="utf-8"；别把它当数据库用。',
  },
  {
    id: 'd-decorator',
    title: '装饰器 @（入门）',
    aliases: ['装饰器', 'decorator', '@', 'wrapper', '包住函数'],
    meaning: '装饰器就是"在不改原函数代码的前提下，给它加一层前后处理"。语法上就是 @名字 写在 def 上面。',
    fixedUsage: '@某装饰器\ndef f(): ...\n# 等价于 f = 某装饰器(f)',
    variants: '加什么前后处理可变。',
    patterns: [
      { name: '现成装饰器', code: '@app.get("/")   # FastAPI 里最常见\n@login_required', note: '真实项目里到处用。' },
      { name: '自己写一个', code: 'def log(func):\n    def wrapper(*a, **k):\n        print("调用", func.__name__)\n        return func(*a, **k)\n    return wrapper\n\n@log\ndef hello(): ...', note: '' },
    ],
    combos: '和 FastAPI 路由一起用；和登录鉴权一起用；读框架源码会遇到。',
    scenarios: ['p3 FastAPI 接口', 'p16 登录鉴权', '读框架源码'],
    pitfalls: '初学者会用现成装饰器就行；自己写要知道 *args/**kwargs；调试时知道 @ 下面包了一层。',
  },
  {
    id: 'd-yield',
    title: '生成器 yield',
    aliases: ['yield', '生成器', 'lazy', 'next', '迭代器'],
    meaning: 'yield 像 return，但每次停在那，下次从停的地方继续。适合"一个一个产数据"而不是一次性塞满内存。',
    fixedUsage: 'def gen():\n    for i in range(10):\n        yield i',
    variants: '产什么、停几次可变。',
    patterns: [
      { name: '一个一个产', code: 'def nums():\n    yield 1\n    yield 2\n\nfor n in nums(): print(n)', note: '' },
      { name: '处理大文件', code: 'def read_lines(path):\n    with open(path) as f:\n        for line in f:\n            yield line.strip()', note: '大文件不占内存。' },
    ],
    combos: '和 for 一起遍历；和文件读大日志；和函数返回值配合。',
    scenarios: ['p17 数仓分批处理', 'p2 读大文件', '读源码遇到 yield'],
    pitfalls: '生成器只能遍历一次；不知道什么时候下一个值就别硬用；初学者先会用就行。',
  },
  {
    id: 'd-select',
    title: 'SQL · SELECT 基础查询',
    aliases: ['select', 'sql', '查询', 'where', 'from', 'where条件', 'SQL'],
    meaning: 'SELECT 是从表里捞数据。基本结构：SELECT 哪些列 FROM 哪个表 WHERE 条件。',
    fixedUsage: 'SELECT 列1, 列2 FROM 表 WHERE 条件;',
    variants: '选哪些列、加不加条件、加不加排序都可变。',
    patterns: [
      { name: '全表', code: 'SELECT * FROM users;', note: '* 表示所有列。' },
      { name: '选列+条件', code: 'SELECT name, age FROM users\nWHERE age >= 18 AND city = "长沙";', note: '' },
      { name: '排序+限量', code: 'SELECT * FROM orders\nORDER BY created_at DESC\nLIMIT 10;', note: '降序取前 10。' },
      { name: '去重', code: 'SELECT DISTINCT city FROM users;', note: '' },
    ],
    combos: '和 WHERE 过滤；和 ORDER BY 排序；和 JOIN 拼多张表；和 group by 汇总。',
    scenarios: ['p1 订单查询', 'p2 取埋点', 'p11 对账查流水'],
    pitfalls: '分号结尾；字符串用引号；WHERE 里不能用列别名；大表别 SELECT *。',
  },
  {
    id: 'd-join',
    title: 'SQL · JOIN 连表',
    aliases: ['join', 'inner join', 'left join', '连表', '关联查询'],
    meaning: 'JOIN 把两张表按"对上的字段"拼起来。INNER JOIN 只要两边都有的；LEFT JOIN 保留左边全部。',
    fixedUsage: 'SELECT a.*, b.*\nFROM 表a a\nJOIN 表b b ON a.id = b.a_id;',
    variants: '连几张表、连什么字段可变。',
    patterns: [
      { name: '内连接', code: 'SELECT o.id, u.name\nFROM orders o\nJOIN users u ON o.user_id = u.id;', note: '两边都有才出现。' },
      { name: '左连接', code: 'SELECT u.name, o.id\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id;', note: '没订单的用户也保留，o.id 是 NULL。' },
    ],
    combos: '和 WHERE 一起过滤；和 GROUP BY 做汇总；和 ON 写连接条件。',
    scenarios: ['p1 订单带用户信息', 'p11 对账多表关联', '数据分析日常'],
    pitfalls: 'ON 和 WHERE 别混；多表 JOIN 字段要加表别名；LEFT JOIN 后右表可能 NULL。',
  },
  {
    id: 'd-groupby',
    title: 'SQL · GROUP BY 聚合',
    aliases: ['group by', '聚合', 'count', 'sum', 'avg', '分组统计', 'having'],
    meaning: 'GROUP BY 把相同值的行归成一组，配合 count/sum/avg 算每组指标。',
    fixedUsage: 'SELECT city, COUNT(*)\nFROM users\nGROUP BY city;',
    variants: '按什么分组、算什么聚合可变。',
    patterns: [
      { name: '计数', code: 'SELECT city, COUNT(*) AS cnt\nFROM users\nGROUP BY city;', note: '' },
      { name: '求和/平均', code: 'SELECT user_id, SUM(amount) AS total\nFROM orders\nGROUP BY user_id;', note: '' },
      { name: '分组后过滤', code: 'SELECT city, COUNT(*) c\nFROM users\nGROUP BY city\nHAVING c > 100;', note: '分组后用 HAVING。' },
    ],
    combos: '和 JOIN 一起；和 WHERE 先过滤再分组；和 ORDER BY 排序结果。',
    scenarios: ['p2 算城市 DAU', 'p7 报表', 'p17 数仓汇总层'],
    pitfalls: 'SELECT 里非聚合列必须出现在 GROUP BY 里；分组后过滤用 HAVING 不是 WHERE。',
  },
  {
    id: 'd-git-basic',
    title: 'Git 基础（add/commit/push）',
    aliases: ['git', 'commit', 'push', 'add', '版本控制', '提交代码'],
    meaning: 'Git 是代码存档工具。改完代码 → add 暂存 → commit 存一次快照 → push 推到远程（GitHub）。',
    fixedUsage: 'git add .\ngit commit -m "说明这次改了啥"\ngit push',
    variants: '改了什么、说明写什么可变。',
    patterns: [
      { name: '首次提交', code: 'git init\ngit add .\ngit commit -m "first commit"\ngit remote add origin 地址\ngit push -u origin main', note: '' },
      { name: '日常提交', code: 'git add 文件名\ngit commit -m "修了登录 bug"\ngit push', note: '' },
      { name: '看状态', code: 'git status      # 改了啥\ngit log --oneline  # 历史', note: '' },
    ],
    combos: '和 GitHub 配合；和分支一起多人协作；和项目 README 一起。',
    scenarios: ['p49 提首个 PR', '所有项目备份', '面试必问'],
    pitfalls: 'commit 信息要写清楚；别 git push --force；提交前先 git status 看清楚。',
  },
  {
    id: 'd-git-branch',
    title: 'Git 分支 branch/merge',
    aliases: ['branch', '分支', 'merge', 'checkout', '切分支', 'PR'],
    meaning: '分支是"平行宇宙"：在新分支上改，不影响主分支 main。改完合并回 main。',
    fixedUsage: 'git switch -c 新分支   # 创建并切过去\n# 改代码\n\ngit switch main\ngit merge 新分支',
    variants: '分支名、合并什么可变。',
    patterns: [
      { name: '开新分支', code: 'git switch -c feature/login\n# 改代码，commit，push\ngit push -u origin feature/login', note: '' },
      { name: '合并', code: 'git switch main\ngit merge feature/login', note: '' },
    ],
    combos: '和 PR 一起：在 GitHub 上提合并请求；和多人协作配合；和 bugfix 分支配合。',
    scenarios: ['p49 开源贡献', 'p13 CI/CD', '团队协作'],
    pitfalls: '切分支前先 commit 或 stash；冲突要手动解决；别直接在 main 上改大功能。',
  },
  {
    id: 'd-linux',
    title: 'Linux 常用命令',
    aliases: ['linux', 'shell', '命令行', 'cd', 'ls', 'grep', 'ps', 'tail', '命令'],
    meaning: 'Linux 服务器全靠命令行操作。最常用：cd 进目录、ls 看文件、看日志、查进程。',
    fixedUsage: 'cd 目录      # 进\nls           # 看文件\npwd          # 当前在哪',
    variants: '路径、文件名可变。',
    patterns: [
      { name: '看文件', code: 'ls -l\ntail -f app.log     # 实时看日志\ncat 文件名          # 全打出来', note: '' },
      { name: '找东西', code: 'grep "error" app.log   # 找报错\nfind . -name "*.py"', note: '' },
      { name: '进程', code: 'ps aux | grep python\nkill 进程号', note: '' },
      { name: '权限/磁盘', code: 'df -h        # 磁盘\nfree -h      # 内存', note: '' },
    ],
    combos: '和 SSH 连服务器；和部署一起；和日志平台配合。',
    scenarios: ['p13 CI/CD', 'p18 监控告警', '所有后端项目'],
    pitfalls: 'rm -rf 别乱敲；路径别写错；先 ls 再删。',
  },
  {
    id: 'd-http',
    title: 'HTTP 与 REST API',
    aliases: ['http', 'API', 'rest', 'get', 'post', '请求', '接口', '状态码', 'request'],
    meaning: '前端和后端通过 HTTP 对话。常用方法：GET 取数据、POST 提交数据、PUT 改、DELETE 删。返回带状态码：200 成功、404 找不到、500 服务器错。',
    fixedUsage: 'GET  /users         # 拿用户列表\nPOST /users         # 新建用户\nGET  /users/1       # 拿 id=1 的用户\nPUT  /users/1       # 改\nDELETE /users/1     # 删',
    variants: '路径、方法可变。',
    patterns: [
      { name: '调 GET', code: 'import requests\nr = requests.get("http://api/users")\nprint(r.status_code)   # 200\nprint(r.json())        # 字典', note: '' },
      { name: '调 POST', code: 'r = requests.post("http://api/users",\n    json={"name": "小明"})', note: 'json= 自动转 JSON。' },
      { name: '前端 fetch', code: 'fetch("/api/progress").then(r=>r.json())', note: '浏览器里的写法。' },
    ],
    combos: '和 JSON 一起收发；和 FastAPI 一起写后端；和前端按钮一起点了请求。',
    scenarios: ['p3 调大模型 API', 'p16 登录接口', 'p6 全栈项目'],
    pitfalls: '404 是路径错；500 是后端崩；跨域 CORS 要后端配；别在前端存密钥。',
  },
  {
    id: 'd-html',
    title: 'HTML 基础标签',
    aliases: ['html', '标签', 'div', 'p', 'h1', 'button', '页面结构', '前端'],
    meaning: 'HTML 是网页骨架。尖括号包起来就是一个标签，成对出现：<div>...</div>。',
    fixedUsage: '<h1>标题</h1>\n<p>一段文字</p>\n<button>按钮</button>\n<div>一块区域</div>',
    variants: '标签内容、属性可变。',
    patterns: [
      { name: '常用结构', code: '<h1>大标题</h1>\n<p>段落</p>\n<a href="https://a.com">链接</a>\n<img src="x.png" />', note: '' },
      { name: '带属性', code: '<input type="text" placeholder="请输入" />\n<button onclick="...">点我</button>', note: '' },
      { name: '块与行', code: '<div>块级：独占一行</div>\n<span>行内：不换行</span>', note: '' },
    ],
    combos: '和 CSS 一起上色排版；和 JS 一起加交互；和 React 一起 JSX。',
    scenarios: ['p6 前端页面', 'p18 落地页', '所有前端项目'],
    pitfalls: '标签要闭合；嵌套别乱；id/class 命名要清晰。',
  },
  {
    id: 'd-css',
    title: 'CSS 选择器与样式',
    aliases: ['css', '样式', '选择器', 'class', 'flex', '颜色', '布局', 'tailwind'],
    meaning: 'CSS 给 HTML 上色、排版、加动画。选择器选中元素，再写属性。',
    fixedUsage: '.类名 { color: red; font-size: 16px; }',
    variants: '选谁、写什么样式可变。',
    patterns: [
      { name: '选元素', code: 'div           # 选所有 div\n.title        # class="title"\n#headline     # id="headline"', note: '' },
      { name: '常用属性', code: 'color: 红色\nfont-size: 16px\nbackground: #eee\npadding: 10px   # 内边距\nmargin: 10px    # 外边距', note: '' },
      { name: 'Flex 布局', code: '.row { display: flex; gap: 8px; }', note: '最常用的横向排版。' },
    ],
    combos: '和 HTML 配合；和 Tailwind 一起（项目里全用 Tailwind）；和组件库一起。',
    scenarios: ['所有前端项目', 'p6 全栈前端', 'p18 落地页'],
    pitfalls: '盒模型 padding/margin 会撑大；Flex 要父元素 display:flex；别同时内联+类选择器乱覆盖。',
  },
  {
    id: 'd-js',
    title: 'JavaScript 基础',
    aliases: ['javascript', 'js', 'const', 'let', '箭头函数', 'array', '对象', '前端'],
    meaning: 'JS 是浏览器里跑的语言。变量用 const（不变）/let（可变）；函数用箭头写法；对象就是字典。',
    fixedUsage: 'const name = "小明"\nlet age = 18\nconst add = (a,b) => a+b',
    variants: '变量名、逻辑可变。',
    patterns: [
      { name: '变量', code: 'const x = 1      // 不重新赋值\nlet y = 2         // 可变', note: '' },
      { name: '数组方法', code: '[1,2,3].map(x => x*2)   // [2,4,6]\n[1,2,3].filter(x => x>1) // [2,3]', note: '和 Python 推导式对应。' },
      { name: '对象', code: 'const u = { name: "小明", age: 18 }\nconsole.log(u.name)', note: '就是 dict。' },
      { name: '异步', code: 'const r = await fetch("/api/x")\nconst data = await r.json()', note: '调接口最常见。' },
    ],
    combos: '和 React 一起写组件；和 fetch 调接口；和 DOM 操作页面。',
    scenarios: ['所有前端项目', 'p6 全栈', 'p18 落地页交互'],
    pitfalls: '== 和 === 区别（用 ===）；异步别忘了 await；undefined 和 null 区分。',
  },
  {
    id: 'd-react',
    title: 'React 组件入门',
    aliases: ['react', '组件', 'jsx', 'useState', 'props', '前端框架'],
    meaning: 'React 把页面拆成一个个组件。组件就是一个函数，返回界面。useState 让界面跟着数据变。',
    fixedUsage: 'function Hello({ name }) {\n  return <div>你好 {name}</div>\n}',
    variants: '组件名、props、界面可变。',
    patterns: [
      { name: '组件', code: 'function Card({ title, children }) {\n  return <div className="card"><h3>{title}</h3>{children}</div>\n}', note: 'props 是参数。' },
      { name: '状态', code: 'const [n, setN] = useState(0)\n<button onClick={() => setN(n+1)}>点 {n}</button>', note: '改 n 界面自动重渲染。' },
    ],
    combos: '和 JSX 写界面；和 API 一起调完 setState；和 Tailwind 写样式。',
    scenarios: ['p6 全栈前端', 'p18 后台', '实战工场本身就是'],
    pitfalls: '组件名首字母大写；state 别直接改（用 setN）；副作用放 useEffect。',
  },
  {
    id: 'd-api-py',
    title: 'Python 发 HTTP 请求 requests',
    aliases: ['requests', 'http库', '调用接口', '调用API', '爬虫', '调大模型'],
    meaning: 'requests 是 Python 调 HTTP 接口的标准库。最常用来调大模型 API、拿网页、和后端对话。',
    fixedUsage: 'import requests\nr = requests.get(url)\nprint(r.json())',
    variants: 'URL、参数、请求体可变。',
    patterns: [
      { name: 'GET 带参数', code: 'r = requests.get("https://api/x", params={"q":"猫"})', note: '' },
      { name: 'POST 带 JSON', code: 'r = requests.post("http://api/chat",\n    headers={"Authorization": "Bearer xxx"},\n    json={"prompt": "你好"})', note: '' },
      { name: '检查成功', code: 'r.raise_for_status()\ndata = r.json()', note: '' },
    ],
    combos: '和 JSON 一起解析返回；和 try/except 处理失败；和大模型 SDK 一起用。',
    scenarios: ['p3 调 OpenAI/豆包 API', 'p6 调自己后端', '爬虫'],
    pitfalls: '超时要设 timeout；密钥别写死在代码里；失败要看 status_code 和返回内容。',
  },
  {
    id: 'd-numpy',
    title: 'NumPy 入门',
    aliases: ['numpy', 'np', '数组', '矩阵', '向量', 'tensor'],
    meaning: 'NumPy 是数值计算基础库，数组 ndarray 比 Python list 快、能批量算。机器学习框架（torch 等）都建立在它之上。',
    fixedUsage: 'import numpy as np\na = np.array([1,2,3])',
    variants: '数组长什么样、做什么运算可变。',
    patterns: [
      { name: '造数组', code: 'np.array([1,2,3])\nnp.zeros((2,3))\nnp.arange(0,10,2)', note: '' },
      { name: '批量运算', code: 'a = np.array([1,2,3])\na * 2        # [2,4,6]\na.mean()     # 2.0', note: '不用写循环。' },
      { name: '矩阵', code: 'm = np.array([[1,2],[3,4]])\nm.shape    # (2,2)', note: '' },
    ],
    combos: '和 pandas 一起（它是底层）；和 matplotlib 画图；和 torch 学深度学习。',
    scenarios: ['p12 推荐算法', 'p28 实验分析', '深度学习入门'],
    pitfalls: '广播规则要懂；形状不匹配会报错；别和 Python list 混着用。',
  },
  {
    id: 'd-matplotlib',
    title: 'matplotlib 画图',
    aliases: ['matplotlib', 'plt', '画图', '折线图', '柱状图', '可视化'],
    meaning: 'matplotlib 是 Python 画图标准库。折线图看趋势、柱状图比大小、饼图看占比。',
    fixedUsage: 'import matplotlib.pyplot as plt\nplt.plot(x, y)\nplt.show()',
    variants: '画什么图、数据可变。',
    patterns: [
      { name: '折线图', code: 'plt.plot([1,2,3], [1,4,9])\nplt.title("趋势")\nplt.savefig("a.png")', note: '' },
      { name: '柱状图', code: 'plt.bar(["A","B"], [10,20])', note: '' },
      { name: '散点图', code: 'plt.scatter(x, y)', note: '' },
    ],
    combos: '和 pandas 一起：df.plot()；和 Jupyter Notebook 一起；写报告插图片。',
    scenarios: ['p7 出报表图', 'p28 AB 结果可视化', 'p12 推荐效果'],
    pitfalls: '中文标题要设字体；savefig 前别 show；图要标清楚坐标轴。',
  },
  {
    id: 'd-llm',
    title: '大模型 API 调用',
    aliases: ['大模型', 'llm', 'openai', 'api key', 'chat completion', 'prompt', '调用大模型'],
    meaning: '调大模型就是发一段对话给它，它返回回答。三段：你的角色设定（system）、历史对话、你这次的问题。',
    fixedUsage: 'response = client.chat.completions.create(\n  model="模型名",\n  messages=[{"role":"user","content":"你好"}]\n)',
    variants: '用什么模型、传什么消息可变。',
    patterns: [
      { name: '最小调用', code: 'from openai import OpenAI\nclient = OpenAI(api_key="...", base_url="...")\nr = client.chat.completions.create(\n    model="doubao-pro",\n    messages=[{"role":"user","content":"讲个笑话"}]\n)\nprint(r.choices[0].message.content)', note: '' },
      { name: '带 system', code: 'messages=[\n  {"role":"system","content":"你是助教，用中文回答"},\n  {"role":"user","content":"什么是变量"}\n]', note: 'system 决定人设。' },
      { name: '流式', code: 'stream = client.chat.completions.create(..., stream=True)\nfor chunk in stream: print(chunk.choices[0].delta.content)', note: '一个字一个字打。' },
    ],
    combos: '和 JSON 一起解析返回；和 requests 兼容写法；和 RAG 把检索到的文档塞进 prompt。',
    scenarios: ['p3 RAG 问答', 'p14 智能客服', 'p19 AI 简历优化'],
    pitfalls: 'API Key 别上传 GitHub；超时要重试；返回格式按官方文档；token 有成本。',
  },
  {
    id: 'd-rag',
    title: 'RAG 检索增强生成',
    aliases: ['rag', '检索增强', '向量库', 'embedding', '知识库问答', 'rag流程'],
    meaning: 'RAG = 先从你的资料里"搜出相关段落"，再把这些段落塞进 prompt 让大模型回答。解决"模型不知道你的私有资料"的问题。',
    fixedUsage: '1. 切文档 → 2. 向量化 → 3. 存向量库\n用户问 → 搜相关段落 → 拼进 prompt → 大模型回答',
    variants: '切多长、用什么向量库、怎么拼 prompt 都可变。',
    patterns: [
      { name: '入库', code: 'chunks = 文档按 500 字切开\nembeddings = 调 embedding 接口\n向量库.add(chunks, embeddings)', note: '' },
      { name: '查询', code: 'q_emb = embed(用户问题)\nhits = 向量库.search(q_emb, k=3)\ncontext = "\\n".join(hits)\nanswer = llm(f"根据：{context}\\n回答：{用户问题}")', note: '' },
    ],
    combos: '和大模型 API 一起；和向量库（FAISS/Chroma）；和文档切分/清洗。',
    scenarios: ['p3 RAG 知识库', 'p14 企业客服', 'p20 文档问答'],
    pitfalls: '切太长模型记不住、太短没上下文；检索不准就答不准；别把无关段落塞太多。',
  },
  {
    id: 'd-embedding',
    title: 'Embedding 向量',
    aliases: ['embedding', '向量', '词向量', '向量数据库', '语义检索'],
    meaning: 'Embedding 把一段话变成一串数字（向量），意思越近的话，向量越接近。用来做"按意思搜"而不是按关键词搜。',
    fixedUsage: 'vec = embed("我喜欢猫")\n# 返回一串浮点数，比如 [0.12, -0.3, ...]',
    variants: '用什么模型、向量维度可变。',
    patterns: [
      { name: '调接口', code: 'resp = client.embeddings.create(\n    model="text-embedding", input="我喜欢猫")\nvec = resp.data[0].embedding', note: '' },
      { name: '算相似度', code: 'from numpy import dot\nsim = dot(a, b) / (norm(a)*norm(b))', note: '余弦相似度。' },
    ],
    combos: '和 RAG 一起；和向量数据库 FAISS/Chroma；和推荐系统。',
    scenarios: ['p3 RAG', 'p12 语义推荐', 'p14 相似问答'],
    pitfalls: '向量是浮点数组不是字符串；不同模型向量不能混比；维度要一致。',
  },
  {
    id: 'd-readme',
    title: 'README 与项目文档',
    aliases: ['readme', '文档', '项目说明', 'gitignore', '提交规范', '项目结构'],
    meaning: 'README 是项目门面：别人打开你的仓库第一眼看到的。写清楚"这是什么、怎么跑、技术栈、截图"。',
    fixedUsage: '# 项目名\n一句话介绍\n\n## 快速开始\n安装 → 配 .env → 跑\n\n## 技术栈\n前端 / 后端 / 数据库',
    variants: '内容怎么组织可变。',
    patterns: [
      { name: '必备段落', code: '## 功能\n## 截图/GIF\n## 技术栈\n## 本地运行\n## 目录结构', note: '' },
      { name: '写怎么跑', code: 'git clone ...\ncd ...\npip install -r requirements.txt\npython main.py', note: '' },
    ],
    combos: '和 Git/GitHub 一起；和简历一起（README 就是简历的实证）；和 PR 描述一起。',
    scenarios: ['所有开源项目', 'p49 首次 PR', '简历项目'],
    pitfalls: '别写空话；有截图就贴截图；命令要真的能跑通；改了功能同步改 README。',
  },
  {
    id: 'd-env',
    title: '环境变量与 .env',
    aliases: ['env', '环境变量', 'api key', '配置', '.env', 'config', 'dotenv'],
    meaning: '把不能写死的东西（密钥、数据库地址）放在 .env 文件里，代码读环境变量。.env 不提交到 Git。',
    fixedUsage: '# .env\nOPENAI_API_KEY=sk-xxx\nDB_URL=sqlite:///x.db',
    variants: '放什么变量可变。',
    patterns: [
      { name: 'Python 读', code: 'from dotenv import load_dotenv\nimport os\nload_dotenv()\nkey = os.getenv("OPENAI_API_KEY")', note: '' },
      { name: '.gitignore', code: '# .gitignore\n.env\n.venv/\n__pycache__/\nnode_modules/', note: '' },
    ],
    combos: '和大模型 API 一起（密钥）；和数据库连接；和部署环境区分 dev/prod。',
    scenarios: ['p3 RAG 项目', 'p6 全栈', '所有真实项目'],
    pitfalls: '密钥千万别 commit；.env 要加 .gitignore；换环境只需改 .env。',
  },
  {
    id: 'd-ab',
    title: 'AB 实验入门',
    aliases: ['ab实验', 'abtest', '对照组', '实验组', '显著性', '指标', '漏斗'],
    meaning: 'AB 实验就是把用户随机分两组：A 组用旧版，B 组用新版，比较关键指标有没有显著差异。',
    fixedUsage: '假设：新版按钮颜色能提高点击率\n分组：50% A（蓝）/ 50% B（红）\n观察：点击 A=2%，B=3.5%\n判断：差异是否显著？',
    variants: '改什么、看什么指标可变。',
    patterns: [
      { name: '核心指标', code: '漏斗：曝光 → 点击 → 注册 → 付费\n看每一步转化率', note: '' },
      { name: '常见指标', code: 'CTR 点击率 = 点击/曝光\n留存 = 第二天回来的人/第一天来的人\n转化率 = 完成目标/进入', note: '' },
    ],
    combos: '和 SQL 一起取数；和 pandas 分析；和假设检验判断。',
    scenarios: ['p28 AB 实验', 'p2 用户增长', 'p7 报表分析'],
    pitfalls: '样本太少别下结论；别同时开太多实验互相干扰；指标要先定义再上线。',
  },
  {
    id: 'd-sql-index',
    title: 'SQL 索引与常见优化',
    aliases: ['索引', 'index', 'explain', '慢查询', '优化', '事务'],
    meaning: '索引像书的目录：在常查的列上建索引，查询快很多。但插入会变慢，别乱建。',
    fixedUsage: 'CREATE INDEX idx_user ON orders(user_id);',
    variants: '在哪个列建可变。',
    patterns: [
      { name: '看执行计划', code: 'EXPLAIN SELECT * FROM orders WHERE user_id=1;', note: '看有没有走索引。' },
      { name: '事务', code: 'BEGIN;\nUPDATE accounts SET money=money-10 WHERE id=1;\nUPDATE accounts SET money=money+10 WHERE id=2;\nCOMMIT;', note: '要么全成，要么全败。' },
    ],
    combos: '和 WHERE 一起；和生产慢查询分析；和锁。',
    scenarios: ['p17 数仓', 'p11 对账', '面试常考'],
    pitfalls: '索引不是越多越好；LIKE "%x%" 用不上索引；大表改表要小心锁。',
  },
  {
    id: 'd-docker',
    title: 'Docker 入门',
    aliases: ['docker', '容器', 'image', 'Dockerfile', '镜像', '部署', 'container'],
    meaning: 'Docker 把"代码 + 环境"打包成一个镜像，在哪跑都一样。解决"我电脑上能跑你那不行"。',
    fixedUsage: '# Dockerfile\nFROM python:3.11\nWORKDIR /app\nCOPY . .\nRUN pip install -r requirements.txt\nCMD ["python", "main.py"]',
    variants: '用什么基础镜像、装什么依赖可变。',
    patterns: [
      { name: '构建运行', code: 'docker build -t myapp .\ndocker run -p 8000:8000 myapp', note: '' },
      { name: '看容器', code: 'docker ps\ndocker logs 容器id', note: '' },
    ],
    combos: '和 CI/CD 一起；和云服务器部署；和团队协作。',
    scenarios: ['p13 CI/CD', 'p18 部署', 'p6 全栈上线'],
    pitfalls: '别把密钥写进镜像；.dockerignore 要写；第一次学先会 build/run 就行。',
  },
  {
    id: 'd-complexity',
    title: '时间复杂度 O(n) 入门',
    aliases: ['复杂度', '时间复杂度', '大O', 'O(n)', 'O(n^2)', 'O(log n)', '算法复杂度'],
    meaning: '复杂度估"数据变大时，代码会慢多少倍"。O(1) 最快、O(log n) 很快、O(n) 线性、O(n^2) 慢。',
    fixedUsage: '一层 for 循环 → O(n)\n两层嵌套 for → O(n^2)\n二分查找 → O(log n)',
    variants: '算法写得好坏决定。',
    patterns: [
      { name: 'O(1)', code: 'x = a[0]', note: '不管多少数据都一步。' },
      { name: 'O(n)', code: 'for x in a: print(x)', note: '数据翻倍，时间翻倍。' },
      { name: 'O(n^2)', code: 'for x in a:\n  for y in a: ...', note: 'n 变 10 倍，慢 100 倍。' },
      { name: 'O(log n)', code: '二分查找', note: '数据变 10 倍只多一步。' },
    ],
    combos: '和数据结构一起选；和面试一起；和大数据量优化。',
    scenarios: ['竞赛：判超时', '面试手写算法', 'p12 推荐算法选型'],
    pitfalls: '别只看代码长短，看循环层数；实际常数也重要但面试先看大 O。',
  },
  {
    id: 'd-array',
    title: '数组与列表（基础数据结构）',
    aliases: ['数组', 'array', 'list', '链表', '栈', '队列', '数据结构'],
    meaning: '数组 = 连续一排格子，按下标 O(1) 取，但中间插入慢。Python list 就是动态数组。栈 = 后进先出；队列 = 先进先出。',
    fixedUsage: 'a = [1,2,3]\na.append(4)    # 尾加 O(1)\na[0]           # 取值 O(1)',
    variants: '存什么可变。',
    patterns: [
      { name: '栈', code: 'stack = []\nstack.append(1); stack.append(2)\nstack.pop()   # 2（后进先出）', note: '' },
      { name: '队列', code: 'from collections import deque\nq = deque([1,2,3])\nq.popleft()   # 1（先进先出）', note: '' },
      { name: '哈希表', code: 'd = {"a":1}\nd["a"]        # 取值 O(1)', note: '就是 dict。' },
    ],
    combos: '和 for 一起遍历；和 dict 做计数；和递归一起。',
    scenarios: ['竞赛：高频题', 'p12 算法', '面试手写'],
    pitfalls: 'list.pop(0) 是 O(n)，用 deque；字典 key 要可哈希；别硬背，会用就行。',
  },
  {
    id: 'd-binary',
    title: '二分查找',
    aliases: ['二分', 'binary search', '查找', '有序', '折半'],
    meaning: '在排好序的数组里，每次砍一半。O(log n)，比从头遍历快得多。',
    fixedUsage: 'lo, hi = 0, len(a)-1\nwhile lo <= hi:\n    mid = (lo+hi)//2\n    if a[mid] == target: return mid\n    elif a[mid] < target: lo = mid+1\n    else: hi = mid-1',
    variants: '找什么可变。',
    patterns: [
      { name: '用库', code: 'import bisect\nbisect.bisect_left(a, target)', note: 'Python 自带。' },
      { name: '手写', code: '见上方模板', note: '' },
    ],
    combos: '和排序一起（必须先排）；和竞赛；和面试手写。',
    scenarios: ['竞赛查找题', '面试高频', '系统设计'],
    pitfalls: '必须先排序；边界 lo/hi 别写错；死循环风险。',
  },
  {
    id: 'd-pytest',
    title: 'pytest 单元测试',
    aliases: ['pytest', '测试', '单测', 'assert', '单元测试', 'tdd', '写测试'],
    meaning: '测试就是"写一段代码自动检查你写的函数对不对"。pytest 是 Python 最常用的测试框架。',
    fixedUsage: 'def add(a,b): return a+b\n\ndef test_add():\n    assert add(1,2) == 3',
    variants: '测什么、断言什么可变。',
    patterns: [
      { name: '最简单测试', code: '# test_calc.py\nfrom calc import add\n\ndef test_add():\n    assert add(1,2) == 3\n    assert add(-1,1) == 0', note: 'pytest 会自动找 test_ 开头。' },
      { name: '跑', code: 'pytest              # 全部\npytest test_calc.py # 指定', note: '' },
    ],
    combos: '和函数一起写；和 CI 一起每次提交自动跑；和重构一起（改完跑测试不怕坏）。',
    scenarios: ['p15 自动化测试', 'p13 CI/CD', '真实项目'],
    pitfalls: '别只测"正常情况"，也要测边界和错误；测试要快；别在测试里 print。',
  },
  {
    id: 'd-cicd',
    title: 'CI/CD 是什么',
    aliases: ['ci', 'cd', 'github actions', '自动化', '流水线', '持续集成'],
    meaning: 'CI/CD 是"每次 push 代码，自动跑测试、自动部署"。GitHub Actions 是最常用的平台。',
    fixedUsage: '.github/workflows/test.yml\n# push 后自动：装依赖 → 跑测试',
    variants: '跑什么步骤可变。',
    patterns: [
      { name: '最小示例', code: 'on: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: pip install -r requirements.txt\n      - run: pytest', note: '' },
    ],
    combos: '和 pytest 一起；和 Git push 触发；和部署一起。',
    scenarios: ['p13 CI/CD 项目', 'p49 开源仓库', '工程化加分项'],
    pitfalls: '先在本地跑通再上 CI；日志要看清楚；别把密钥写进 yml。',
  },
  {
    id: 'd-resume',
    title: '简历项目怎么写',
    aliases: ['简历', '项目描述', 'STAR', '怎么写项目', '简历项目', '简历包装'],
    meaning: '简历写项目用 STAR：背景(Situation)→任务(Task)→动作(Action)→结果(Result)。量化结果，别写"负责后端开发"。',
    fixedUsage: '我做了 X 项目，用了 A+B 技术，解决了 Y 问题，把 Z 从 a 提到 b。',
    variants: '每个项目不一样。',
    patterns: [
      { name: '差写法', code: '负责后端开发，写了接口，用了 Python。', note: '' },
      { name: '好写法', code: '独立开发 RAG 知识库问答系统：接入 XX 文档 1 万篇，\n用 FAISS 做向量检索，接入豆包大模型，\n首答准确率从 62% 提到 87%，响应 <2s。', note: '' },
    ],
    combos: '和 README 对应；和面试讲项目对应；和 GitHub 仓库对应。',
    scenarios: ['简历', '面试', 'p49 开源'],
    pitfalls: '别写没真做过的；数字要能圆；技术栈别乱写；一行一个亮点。',
  },
  {
    id: 'd-interview',
    title: '面试怎么讲项目',
    aliases: ['面试', '讲项目', '面试题', '自我介绍', '项目复盘', '被问怎么办'],
    meaning: '讲项目按"一句话是什么 → 技术栈 → 我做了什么 → 遇到什么难点怎么解决 → 结果"。被问倒就说思路，别硬编。',
    fixedUsage: '1. 这个项目是干什么的（30 秒）\n2. 技术栈\n3. 我负责哪块\n4. 最大难点 + 怎么解决\n5. 结果/反思',
    variants: '项目不同内容不同。',
    patterns: [
      { name: '被问"为什么选这个方案"', code: '对比过 A 和 B，因为 X 选了 B。', note: '' },
      { name: '被问"遇到什么 bug"', code: '具体现象 → 怎么定位 → 怎么修 → 学到什么。', note: '' },
    ],
    combos: '和简历一起；和 README 一起；和复盘文档一起。',
    scenarios: ['所有面试', '实习面试', '校招'],
    pitfalls: '别说前同事坏话；别吹自己；被问住就说"这块我当时是 X，换现在我会 Y"。',
  },
  {
    id: 'd-nginx',
    title: 'Nginx 与部署入门',
    aliases: ['nginx', '部署', '服务器', '反向代理', '上线', '域名'],
    meaning: 'Nginx 是一个"门卫"：用户访问域名时，它接收请求，转给你的后端程序，还能托管前端静态文件。',
    fixedUsage: 'server {\n  listen 80;\n  server_name example.com;\n  location / {\n    proxy_pass http://127.0.0.1:8000;\n  }\n}',
    variants: '域名、后端地址可变。',
    patterns: [
      { name: '反代后端', code: 'location /api/ {\n  proxy_pass http://127.0.0.1:8000/;\n}', note: '' },
      { name: '托管前端', code: 'location / {\n  root /usr/share/nginx/html;\n  try_files $uri /index.html;\n}', note: '' },
    ],
    combos: '和云服务器一起；和域名解析；和 HTTPS。',
    scenarios: ['p18 部署上线', 'p6 全栈上线', 'p13 CI/CD'],
    pitfalls: '改完 nginx -t 检查再 reload；防火墙要开 80/443；静态文件路径别写错。',
  },
  {
    id: 'd-recursion',
    title: '递归入门',
    aliases: ['递归', 'recursion', '斐波那契', '自己调自己', '回溯'],
    meaning: '递归就是函数自己调自己，把大问题拆成一模一样的小问题。必须有"出口"（不再递归的情况），否则死循环。',
    fixedUsage: 'def f(n):\n    if 出口: return 0\n    return f(n-1)',
    variants: '拆成几小步、出口是什么可变。',
    patterns: [
      { name: '阶乘', code: 'def fact(n):\n    if n <= 1: return 1\n    return n * fact(n-1)\n\nfact(5)   # 120', note: '' },
      { name: '斐波那契', code: 'def fib(n):\n    if n <= 2: return 1\n    return fib(n-1) + fib(n-2)', note: '面试常考。' },
    ],
    combos: '和树/图遍历一起；和分治；和记忆化优化。',
    scenarios: ['竞赛：树/回溯题', '面试手写', 'p12 算法'],
    pitfalls: '没出口会爆栈；深度大要改迭代；别瞎用，能循环就循环。',
  },
  {
    id: 'd-window',
    title: 'SQL 窗口函数',
    aliases: ['窗口函数', 'window', 'row_number', 'rank', 'over', 'partition by'],
    meaning: '窗口函数在"不合并行"的前提下做排名/累计。最常用 row_number() 给每行编个号。',
    fixedUsage: 'SELECT *,\n  ROW_NUMBER() OVER (PARTITION BY city ORDER BY age DESC) AS rn\nFROM users;',
    variants: '按什么分组、按什么排序可变。',
    patterns: [
      { name: '组内排名', code: 'SELECT city, name, age,\n  RANK() OVER (PARTITION BY city ORDER BY age DESC) AS rk\nFROM users;', note: '每个城市里排年龄。' },
      { name: '累计', code: 'SELECT day, amount,\n  SUM(amount) OVER (ORDER BY day) AS cum\nFROM sales;', note: '每天累计销售额。' },
    ],
    combos: '和 GROUP BY 对比（窗口不合并行）；和取 TopN；和报表。',
    scenarios: ['p17 数仓', '面试高频', 'p7 报表'],
    pitfalls: '窗口函数不能写在 WHERE 里；PARTITION BY 别忘；CTE 里常用。',
  },
  {
    id: 'd-fastapi',
    title: 'FastAPI 路由入门',
    aliases: ['fastapi', 'flask', '后端框架', '路由', 'api路由', 'uvicorn', 'web框架'],
    meaning: 'FastAPI 是 Python 现代后端框架，几行代码就能起一个 HTTP 服务，自动生成接口文档。',
    fixedUsage: 'from fastapi import FastAPI\napp = FastAPI()\n\n@app.get("/hello")\ndef hello():\n    return {"msg": "你好"}',
    variants: '路径、方法、返回什么可变。',
    patterns: [
      { name: '带参数', code: '@app.get("/users/{uid}")\ndef get_user(uid: int):\n    return {"id": uid}', note: '' },
      { name: 'POST 接 JSON', code: 'from pydantic import BaseModel\nclass Item(BaseModel):\n    name: str\n\n@app.post("/items")\ndef create(item: Item):\n    return item', note: '' },
      { name: '跑', code: 'uvicorn main:app --reload\n# 访问 http://localhost:8000/docs', note: '自动文档。' },
    ],
    combos: '和 SQLAlchemy 连数据库；和 JWT 登录；和部署到服务器。',
    scenarios: ['p6 全栈项目', 'p16 登录后端', 'p3 把 RAG 包成 API'],
    pitfalls: '路径别重复；返回 dict 自动变 JSON；Pydantic 模型定义清楚。',
  },
  {
    id: 'd-jwt',
    title: 'JWT 登录入门',
    aliases: ['jwt', '登录', 'token', '认证', '鉴权', 'session'],
    meaning: 'JWT 是"登录后发一串令牌"，之后每次请求带上它，后端就知道你是谁。无状态，适合前后端分离。',
    fixedUsage: '登录成功 → 发 token\n下次请求头：Authorization: Bearer <token>\n后端验 token → 知道 user_id',
    variants: '存什么信息、过期多久可变。',
    patterns: [
      { name: '签发', code: 'import jwt\ntoken = jwt.encode({"user_id": 1}, "secret", algorithm="HS256")', note: '' },
      { name: '验证', code: 'data = jwt.decode(token, "secret", algorithms=["HS256"])\nuid = data["user_id"]', note: '' },
    ],
    combos: '和 FastAPI 依赖注入一起；和前端 localStorage；和密码哈希。',
    scenarios: ['p16 登录注册', 'p6 全栈', '所有需要登录的项目'],
    pitfalls: 'secret 别写死；HTTPS 才安全；过期时间别太长。',
  },
  {
    id: 'd-stats',
    title: '描述统计与分布',
    aliases: ['均值', '方差', '标准差', '正态分布', '中位数', 'percentile'],
    meaning: '描述一组数据：均值是中心、方差/标准差是分散程度、中位数不受极端值影响。',
    fixedUsage: 'import statistics as s\ns.mean([1,2,3])\ns.stdev([1,2,3])',
    variants: '算什么可变。',
    patterns: [
      { name: '用 pandas', code: 'df["age"].mean()\ndf["age"].median()\ndf["age"].std()\ndf["age"].describe()', note: '一行看全。' },
      { name: '分位数', code: 'df["age"].quantile(0.95)', note: '前 5% 是多大。' },
    ],
    combos: '和 AB 实验一起；和数据清洗；和报表。',
    scenarios: ['p28 AB 分析', 'p2 用户分析', 'p17 数仓'],
    pitfalls: '均值被极端值拉偏；收入类用中位数；标准差和方差差平方关系。',
  },
  {
    id: 'd-hypothesis',
    title: '假设检验入门',
    aliases: ['假设检验', 'p值', 'p-value', '显著性', 't检验', '置信区间', 'ab显著性'],
    meaning: 'AB 实验后问："两组差异是真的，还是只是运气？" p 值 < 0.05 通常认为"显著，不是运气"。',
    fixedUsage: 'H0: 两组没差异\nH1: 两组有差异\n算 p 值，<0.05 就拒绝 H0',
    variants: '用什么检验看数据类型。',
    patterns: [
      { name: '两比例检验', code: 'from statsmodels.stats.proportion import proportions_ztest\n# 点击率 A 200/1000, B 350/1000\nz, p = proportions_ztest([200,350],[1000,1000])', note: '' },
      { name: '看 p', code: 'if p < 0.05: print("显著")\nelse: print("不显著，继续观察")', note: '' },
    ],
    combos: '和 AB 实验一起；和 pandas；和业务决策。',
    scenarios: ['p28 AB', 'p2 增长实验', '面试常问'],
    pitfalls: 'p<0.05 不代表业务上重要；样本要够；别反复刷 p 值；实验要先定指标。',
  },
  {
    id: 'd-react-hooks',
    title: 'React Hooks 入门',
    aliases: ['useEffect', 'hook', 'useState', 'useRef', '生命周期'],
    meaning: 'Hooks 是函数组件里"加状态和副作用"的工具。useState 管数据；useEffect 在渲染后做事（比如调接口）。',
    fixedUsage: 'const [n, setN] = useState(0)\nuseEffect(() => { /* 副作用 */ }, [依赖])',
    variants: '依赖数组写什么可变。',
    patterns: [
      { name: '调接口', code: 'useEffect(() => {\n  fetch("/api/user").then(r=>r.json()).then(setUser)\n}, [])', note: '空依赖 = 只跑一次。' },
      { name: '监听变化', code: 'useEffect(() => {\n  document.title = `你点了 ${n} 次`\n}, [n])', note: 'n 变就跑。' },
    ],
    combos: '和 fetch 一起；和组件卸载清理；和表单。',
    scenarios: ['所有 React 项目', '实战工场本身', 'p6 全栈'],
    pitfalls: '依赖数组别乱填也别漏；不要在 useEffect 里写 render 必要的计算；别在循环里调 hook。',
  },
  {
    id: 'd-sqlalchemy',
    title: 'SQLAlchemy ORM 入门',
    aliases: ['sqlalchemy', 'orm', '模型', '数据库映射', 'pandas to sql'],
    meaning: 'ORM 让你用 Python 对象操作数据库，不用手写 SQL。表 = 类，行 = 对象。',
    fixedUsage: 'class User(Base):\n    __tablename__ = "users"\n    id = Column(Integer, primary_key=True)\n    name = Column(String)',
    variants: '表结构、字段可变。',
    patterns: [
      { name: '建表', code: 'Base.metadata.create_all(engine)', note: '' },
      { name: '查', code: 'session.query(User).filter(User.name=="小明").first()', note: '' },
      { name: '加', code: 'u = User(name="小红")\nsession.add(u); session.commit()', note: '' },
    ],
    combos: '和 FastAPI 一起；和 SQLite/Postgres；和迁移工具 Alembic。',
    scenarios: ['p6 全栈', 'p11 对账系统', 'p16 登录存用户'],
    pitfalls: '别在循环里查 N+1；session 要关；迁移比手写 SQL 安全。',
  },
  {
    id: 'd-https',
    title: 'HTTPS 与 Cookie/Token',
    aliases: ['https', 'http协议', 'cookie', 'token', '跨域', 'cors', 'session'],
    meaning: 'HTTPS 是加密的 HTTP（地址栏小锁）。Cookie 是浏览器自动存的小文本；Token 是登录后自己带在请求头里的凭证。',
    fixedUsage: 'Cookie: 浏览器自动带\nAuthorization: Bearer <token>  手动带',
    variants: '存哪、怎么带可变。',
    patterns: [
      { name: '前端带 token', code: 'fetch("/api/me", {\n  headers: {"Authorization": "Bearer " + token}\n})', note: '' },
      { name: '后端开 CORS', code: 'from fastapi.middleware.cors import CORSMiddleware\napp.add_middleware(CORSMiddleware, allow_origins=["*"])', note: '开发期用。' },
    ],
    combos: '和 JWT 一起；和登录；和前后端分离。',
    scenarios: ['p6 全栈', 'p16 登录', '所有上线项目'],
    pitfalls: 'CORS 是浏览器拦的，不是后端；本地 8000/23456 跨端口要配；生产别 allow_origins=["*"]。',
  },
  {
    id: 'd-sliding',
    title: '双指针与滑动窗口',
    aliases: ['双指针', '滑动窗口', 'two pointer', 'sliding window', '相向指针'],
    meaning: '在数组上用两个指针往中间/同向走，一次遍历解决问题，避免 O(n^2)。',
    fixedUsage: '左指针在左，右指针在右，按条件移动其中一个。',
    variants: '怎么移动、窗口大小可变。',
    patterns: [
      { name: '相向：两数之和（有序）', code: 'lo, hi = 0, len(a)-1\nwhile lo < hi:\n    s = a[lo] + a[hi]\n    if s == target: return [lo,hi]\n    elif s < target: lo += 1\n    else: hi -= 1', note: '' },
      { name: '同向：最长无重复子串', code: 'window = {}\nleft = 0\nfor right, c in enumerate(s): ...', note: '' },
    ],
    combos: '和排序一起；和哈希表计数；和竞赛高频。',
    scenarios: ['竞赛刷题', '面试手写', 'p12 算法'],
    pitfalls: '必须有序才能用相向；窗口收缩条件别写错；先画图再写。',
  },
  {
    id: 'd-dfs',
    title: 'DFS / BFS 入门',
    aliases: ['dfs', 'bfs', '深度优先', '广度优先', '图遍历', '树遍历', '递归遍历'],
    meaning: 'DFS 一路走到黑再回头（递归/栈）；BFS 一层一层走（队列）。用来遍历树/图/网格。',
    fixedUsage: 'DFS：栈或递归\nBFS：队列',
    variants: '遍历什么可变。',
    patterns: [
      { name: '树 DFS', code: 'def dfs(node):\n    if not node: return\n    print(node.val)\n    dfs(node.left)\n    dfs(node.right)', note: '' },
      { name: '网格 BFS', code: 'from collections import deque\nq = deque([起点])\nwhile q:\n    x, y = q.popleft()\n    for 邻居: q.append(邻居)', note: '最短距离常用。' },
    ],
    combos: '和递归；和 visited 集合防重复；和竞赛。',
    scenarios: ['竞赛：树/图/迷宫', '面试高频', 'p12 算法'],
    pitfalls: 'BFS 找最短；DFS 找路径；visited 别忘；网格越界要判断。',
  },
  {
    id: 'd-lint',
    title: '代码风格与 Lint',
    aliases: ['lint', 'eslint', 'prettier', '代码规范', '格式化', '代码风格'],
    meaning: 'Lint 自动检查代码错误和风格（少分号、未用变量）；Prettier 自动格式化。团队合作时必须统一。',
    fixedUsage: 'npx eslint src      # 检查\nnpx eslint src --fix # 自动修',
    variants: '规则怎么配可变。',
    patterns: [
      { name: '跑 lint', code: 'npm run lint', note: '' },
      { name: '编辑器集成', code: 'VSCode 装 ESLint + Prettier 插件，保存自动格式化', note: '' },
    ],
    combos: '和 CI 一起（CI 里跑 lint）；和 Code Review；和团队规范。',
    scenarios: ['所有团队项目', 'p13 工程化', '开源贡献'],
    pitfalls: '别手改格式，用 --fix；规则要团队一致；别把 warning 当没事。',
  },
  {
    id: 'd-cv',
    title: '实习/校招时间线',
    aliases: ['实习', '校招', '找工作', '秋招', '春招', '投递', '笔试', 'offer'],
    meaning: '校招节奏：暑假前找日常实习 → 暑假转正/秋招提前批 → 9-11 月秋招 → 次年 3-4 月春招。越早准备越好。',
    fixedUsage: '大二下：刷算法+做项目\n大三暑假：日常/暑期实习\n大四秋招：9-11 月',
    variants: '个人节奏不同。',
    patterns: [
      { name: '准备清单', code: '1. 简历 1 页\n2. 2-3 个能讲的项目\n3. 算法题刷 100-200\n4. SQL 写熟', note: '' },
    ],
    combos: '和简历；和项目；和 LeetCode 刷题。',
    scenarios: ['求职', '实习', '校招'],
    pitfalls: '别海投；实习比自学重要；简历别造假；早投。',
  },
  {
    id: 'd-leetcode',
    title: 'LeetCode 刷题方法',
    aliases: ['leetcode', '刷题', '算法题', '力扣', '笔试题', 'oj'],
    meaning: '刷题不是刷量，是按题型套路刷。高频：数组、哈希、双指针、二叉树、DP 入门。',
    fixedUsage: '按专题刷 → 每题写思路 → 二刷复习',
    variants: '刷什么专题可变。',
    patterns: [
      { name: '推荐顺序', code: '数组 → 哈希表 → 双指针 → 二分 → 二叉树 → 递归 → DP入门', note: '' },
      { name: '怎么刷', code: '1. 先想 15 分钟\n2. 看题解\n3. 自己重写\n4. 一周后再写一次', note: '' },
    ],
    combos: '和面试；和竞赛；和简历项目。',
    scenarios: ['笔试', '面试', '竞赛'],
    pitfalls: '别死磕一道；别只看不动手；按题型刷别随机刷。',
  },
  {
    id: 'd-cloud',
    title: '云服务器与部署清单',
    aliases: ['云服务器', 'ecs', '阿里云', '腾讯云', '域名', '备案', '服务器'],
    meaning: '把后端跑在云服务器上，买一台 → SSH 上去 → 装环境 → 跑程序 → 用 Nginx 转发。',
    fixedUsage: '买 ECS → SSH 连上去 → 装 Python/Node → 跑你的后端 → Nginx 反代',
    variants: '买哪家、配置可变。',
    patterns: [
      { name: 'SSH 连', code: 'ssh root@你的IP', note: '' },
      { name: '装环境', code: 'apt update\napt install python3-pip nginx\ngit clone 你的仓库', note: '' },
      { name: '常驻', code: '用 systemd 或 pm2 让进程后台跑', note: '' },
    ],
    combos: '和 Docker；和 Nginx；和域名备案。',
    scenarios: ['p18 部署', 'p6 上线', '简历项目上线'],
    pitfalls: '密码别用弱密码；开密钥登录；备案要时间（国内）；安全组开端口。',
  },
  {
    id: 'd-prompt',
    title: 'Prompt 工程入门',
    aliases: ['prompt', '提示词', '提示工程', '怎么写提示', '调prompt', '系统提示'],
    meaning: 'Prompt 是你给大模型的指令。写好 Prompt = 给清楚角色、任务、格式、示例，模型答得更好。',
    fixedUsage: '角色 + 任务 + 输入 + 输出格式 + 示例',
    variants: '怎么写可变。',
    patterns: [
      { name: '结构', code: '你是 XX 助教。\n任务：回答用户关于 Python 的问题。\n要求：用中文，代码用 ``` 包起来。\n问题：{用户问题}', note: '' },
      { name: '给示例 few-shot', code: '示例 1：\n输入：1+1\n输出：2\n现在：{新输入}', note: '' },
    ],
    combos: '和 RAG 一起（拼 context）；和函数调用；和 Agent。',
    scenarios: ['p3 RAG', 'p14 客服', 'p19 简历优化'],
    pitfalls: '别含糊；要什么格式就写清楚；太长模型会忘；多试几版。',
  },
  {
    id: 'd-funcall',
    title: 'Function Calling 函数调用',
    aliases: ['function calling', '函数调用', '工具调用', 'tool use', '大模型调用工具'],
    meaning: '让大模型不光说话，还能"调函数"：你告诉它有哪些函数可用，它自己判断什么时候调、传什么参数，你执行后把结果再给它。',
    fixedUsage: '定义工具 schema → 发给模型 → 模型返回 tool_calls → 你执行函数 → 结果回填 → 模型生成最终回答',
    variants: '定义哪些工具、怎么执行可变。',
    patterns: [
      { name: '定义工具', code: 'tools=[{\n  "type":"function",\n  "function":{\n    "name":"get_weather",\n    "parameters":{"type":"object","properties":{"city":{"type":"string"}}}\n  }\n}]', note: '' },
      { name: '循环执行', code: 'resp = client.chat.completions.create(messages=msgs, tools=tools)\nif resp.choices[0].finish_reason == "tool_calls":\n    for tc in resp.choices[0].message.tool_calls:\n        结果 = 你的函数(tc.function.arguments)\n        msgs.append({"role":"tool","content":str(结果),...})', note: '' },
    ],
    combos: '和 RAG 一起（工具 = 检索）；和数据库查询；和 Agent。',
    scenarios: ['p14 智能客服调天气/查订单', 'p20 文档 Agent', 'p3 RAG 升级版'],
    pitfalls: '函数要真能跑；参数要校验；别让模型乱调；结果要回填。',
  },
  {
    id: 'd-agent',
    title: 'Agent 智能体入门',
    aliases: ['agent', '智能体', 'autonomous', '规划', 'react', '自主'],
    meaning: 'Agent = 大模型 + 工具 + 循环：模型自己想下一步该做什么、调什么工具、看结果、再决定，直到完成任务。',
    fixedUsage: '用户目标 → 模型思考 → 调工具 → 看结果 → 再思考 → ... → 完成',
    variants: '给什么工具、怎么终止可变。',
    patterns: [
      { name: '最小循环', code: 'while not done:\n    thought = llm.think(目标, 历史)\n    action = thought.action\n    result = 执行(action)\n    历史.append(result)', note: '' },
    ],
    combos: '和 Function Calling 一起；和 RAG；和多工具组合。',
    scenarios: ['p14 客服 Agent', 'p20 文档 Agent', '简历项目亮点'],
    pitfalls: '容易无限循环；要设最大步数；工具要少而精；不是万能。',
  },
  {
    id: 'd-router',
    title: 'React Router 路由',
    aliases: ['react router', '路由', 'router', '页面跳转', 'link', 'navigate'],
    meaning: '单页应用里"切页面"不真的刷新，靠路由切换组件。/skills 显示技能页、/projects 显示项目页。',
    fixedUsage: '<Routes>\n  <Route path="/" element={<Home/>}/>\n  <Route path="/skills" element={<Skills/>}/>\n</Routes>',
    variants: '路径、组件可变。',
    patterns: [
      { name: '配置', code: '<Route path="/projects/:id" element={<Detail/>}/>', note: ':id 是参数。' },
      { name: '跳转', code: 'import { useNavigate } from "react-router-dom"\nconst nav = useNavigate()\nnav("/skills")', note: '' },
      { name: '取参数', code: 'const { id } = useParams()', note: '' },
    ],
    combos: '和页面组件；和导航栏；和鉴权（未登录跳登录页）。',
    scenarios: ['实战工场本身', 'p6 全栈前端', 'p18 后台'],
    pitfalls: '嵌套路由别忘 Outlet；404 要配 * 路由；参数是字符串。',
  },
  {
    id: 'd-logging',
    title: '日志 logging',
    aliases: ['logging', '日志', 'print', 'logger', 'debug日志', 'log'],
    meaning: '正式项目别用 print，用 logging：分级（DEBUG/INFO/WARNING/ERROR）、能写文件、能搜。',
    fixedUsage: 'import logging\nlogging.basicConfig(level=logging.INFO)\nlogging.info("启动了")',
    variants: '级别、输出到哪可变。',
    patterns: [
      { name: '基础', code: 'import logging\nlogging.basicConfig(\n  filename="app.log",\n  format="%(asctime)s %(levelname)s %(message)s",\n  level=logging.INFO)', note: '' },
      { name: '各级别', code: 'logging.debug("调试")\nlogging.info("信息")\nlogging.warning("警告")\nlogging.error("错了")', note: '' },
    ],
    combos: '和 try/except 一起记错误；和部署后排查；和监控。',
    scenarios: ['所有后端项目', 'p13 部署后查错', 'p16 线上故障'],
    pitfalls: '别在日志里打密码/Token；别用 print 记业务日志；级别别全 DEBUG。',
  },
  {
    id: 'd-gradient',
    title: '梯度下降入门',
    aliases: ['梯度下降', 'gradient descent', 'loss', '损失函数', '学习率', '优化器'],
    meaning: '训练模型就是"调参数让 loss 变小"。梯度告诉你往哪走能让 loss 下降，学习率是步子大小。',
    fixedUsage: 'repeat:\n    梯度 = 算损失对参数的导数\n    参数 -= 学习率 * 梯度',
    variants: '学习率多大、模型什么可变。',
    patterns: [
      { name: '直觉', code: '站在山上，最陡方向下山，\n学习率 = 一步迈多大', note: '' },
      { name: '关键概念', code: 'loss: 模型错多少\n梯度: 往哪走错更少\n学习率: 步子大小\nepoch: 把数据看一遍', note: '' },
    ],
    combos: '和 PyTorch；和神经网络；和大模型微调。',
    scenarios: ['p10 深度学习入门', 'p12 推荐算法', 'AI 岗面试'],
    pitfalls: '学习率太大不收敛、太小慢；别背公式，先直觉；别和反向传播混。',
  },
  {
    id: 'd-pytorch',
    title: 'PyTorch 入门',
    aliases: ['pytorch', 'torch', 'tensor', '神经网络', '深度学习框架'],
    meaning: 'PyTorch 是最流行的深度学习框架。核心是 Tensor（多维数组，会自动求导）。',
    fixedUsage: 'import torch\nx = torch.tensor([1.0, 2.0])\ny = x * 2',
    variants: '模型结构、数据可变。',
    patterns: [
      { name: '张量', code: 'x = torch.randn(3, 4)  # 3x4 随机', note: '' },
      { name: '自动求导', code: 'w = torch.tensor(1.0, requires_grad=True)\ny = w**2\ny.backward()\nprint(w.grad)   # 2.0', note: '' },
      { name: '训练循环', code: 'for epoch in range(10):\n    out = model(x)\n    loss = loss_fn(out, y)\n    opt.zero_grad()\n    loss.backward()\n    opt.step()', note: '' },
    ],
    combos: '和 NumPy 对比；和神经网络层；和 GPU。',
    scenarios: ['p10 深度学习', 'AI 岗', '论文复现'],
    pitfalls: '显存不够别 batch 太大；.item() 取值；别在训练循环里 print 太多。',
  },
  {
    id: 'd-vector-db',
    title: '向量数据库（FAISS/Chroma）',
    aliases: ['faiss', 'chroma', '向量库', '向量检索', 'vector db', 'rag存储'],
    meaning: '向量数据库存"一堆向量 + 原文"，能快速找出和查询向量最像的 TopK。是 RAG 的存储层。',
    fixedUsage: '存：add(原文, 向量)\n查：search(查询向量, k=5)',
    variants: '用哪个库、存什么可变。',
    patterns: [
      { name: 'Chroma', code: 'import chromadb\nclient = chromadb.PersistentClient("./db")\ncol = client.get_or_create_collection("docs")\ncol.add(documents=[...], embeddings=[...], ids=[...])\nres = col.query(query_embeddings=[q_vec], n_results=5)', note: '' },
      { name: 'FAISS', code: 'import faiss\nindex = faiss.IndexFlatL2(dim)\nindex.add(向量矩阵)\nD, I = index.search(q_vec, 5)', note: '' },
    ],
    combos: '和 Embedding 一起；和 RAG；和大模型。',
    scenarios: ['p3 RAG', 'p14 客服知识库', '简历项目'],
    pitfalls: '向量维度要一致；别自己写暴力检索；删改要自己处理；生产用专业库。',
  },
  {
    id: 'd-mlflow',
    title: 'ML 项目结构与实验跟踪',
    aliases: ['实验跟踪', 'mlflow', 'wandb', '项目结构', '机器学习工程化'],
    meaning: 'ML 项目不能只写个 notebook。标准结构：data/ models/ src/ notebooks/ configs/，每次实验记录参数和指标。',
    fixedUsage: 'project/\n  data/\n  models/\n  src/\n  configs/\n  train.py\n  eval.py',
    variants: '结构怎么组织可变。',
    patterns: [
      { name: '记录实验', code: 'import mlflow\nmlflow.log_param("lr", 0.01)\nmlflow.log_metric("acc", 0.87)', note: '' },
    ],
    combos: '和模型训练；和论文复现；和简历项目。',
    scenarios: ['p10 深度学习', 'p12 推荐', 'AI 岗简历'],
    pitfalls: '别把数据集传 Git；随机种子要固定；实验要能复现。',
  },
  {
    id: 'd-java',
    title: 'Java 入门（企业主力后端）',
    aliases: ['java', 'jvm', '类', 'main方法', '后端语言', '企业后端'],
    meaning: 'Java 是企业后端最主流语言之一。强类型、编译成 class 跑在 JVM 上。一切写在类里，程序从 main 方法开始。',
    fixedUsage: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("你好");\n    }\n}',
    variants: '类名、方法体可变；语法比 Python 严格。',
    patterns: [
      { name: '变量', code: 'int age = 18;\nString name = "小明";\nList<String> list = new ArrayList<>();', note: '要写类型。' },
      { name: '方法', code: 'public int add(int a, int b) {\n    return a + b;\n}', note: '' },
      { name: '编译运行', code: 'javac Main.java\njava Main', note: '' },
    ],
    combos: '和 Spring Boot 写后端；和 Maven/Gradle 管理依赖；和 MySQL。',
    scenarios: ['后端校招', 'Java 岗', '大厂服务端'],
    pitfalls: '分号别漏；类型要对；空指针 NullPointerException 最常见；别和 JavaScript 混。',
  },
  {
    id: 'd-cpp',
    title: 'C++ 入门（竞赛/高性能）',
    aliases: ['c++', 'cpp', '竞赛语言', '指针', '内存', 'acm'],
    meaning: 'C++ 是竞赛（NOI/ICPC）和高性能后端用的语言。比 Python 快，但要自己管内存。',
    fixedUsage: '#include <iostream>\nusing namespace std;\nint main() {\n    cout << "你好" << endl;\n    return 0;\n}',
    variants: '逻辑可变；头文件要 include。',
    patterns: [
      { name: '读入输出', code: 'int a, b;\ncin >> a >> b;\ncout << a + b << endl;', note: '竞赛最常写。' },
      { name: 'vector', code: '#include <vector>\nvector<int> v = {1,2,3};\nv.push_back(4);', note: '动态数组。' },
      { name: '编译', code: 'g++ main.cpp -o main -O2\n./main', note: '' },
    ],
    combos: '和算法竞赛；和 STL（sort/vector/map）；和高性能服务。',
    scenarios: ['竞赛：LeetCode/NOI', '游戏后端', '嵌入式/高性能'],
    pitfalls: '数组越界；忘 free/delete；编译错误信息长；用 g++ -O2。',
  },
  {
    id: 'd-ts',
    title: 'TypeScript 入门',
    aliases: ['typescript', 'ts', '类型', 'interface', '前端类型'],
    meaning: 'TS = JS + 类型。写代码时给变量标类型，写错了编译期就报错，比 JS 健壮。React/Vue 现在都推荐 TS。',
    fixedUsage: 'interface User {\n  name: string;\n  age: number;\n}\nconst u: User = { name: "小明", age: 18 };',
    variants: '类型怎么定义可变。',
    patterns: [
      { name: '基本类型', code: 'const n: number = 1\nconst s: string = "a"\nconst b: boolean = true', note: '' },
      { name: '函数', code: 'function add(a: number, b: number): number {\n  return a + b;\n}', note: '' },
      { name: '数组', code: 'const list: number[] = [1,2,3]', note: '' },
    ],
    combos: '和 React 一起写组件 props；和接口响应；和 IDE 提示。',
    scenarios: ['所有现代前端项目', 'p6 全栈', '实战工场本身'],
    pitfalls: 'any 别乱用；可选属性加 ?；接口和类型别混；先会基础再上泛型。',
  },
];
// ---------- 检索 ----------
interface FlatDive {
  lessonId: string;
  dive: ILessonDeepDive;
  haystack: string;
}

const FLAT: FlatDive[] = Object.entries(ATOMIC_DIVES).flatMap(([lessonId, list]) =>
  list.map((dive) => ({
    lessonId,
    dive,
    haystack: `${dive.point} ${dive.formalDef} ${dive.fixed} ${dive.variable} ${dive.rookie} ${dive.realWorld} ${dive.examples.map((e) => e.code).join(' ')}`.toLowerCase(),
  }))
);

function score(q: string, hay: string): number {
  const query = q.toLowerCase().trim();
  if (!query) return 0;
  let s = 0;
  if (hay.includes(query)) s += 10;
  const symbols = query.match(/[a-zA-Z_][a-zA-Z0-9_]*|==|!=|<=|>=|\+\+|--|\. |\(\)|__\w+__/g) ?? [];
  for (const sym of symbols) {
    if (sym.length < 2) continue;
    if (hay.includes(sym.toLowerCase())) s += 3;
  }
  const chars = Array.from(new Set(query.replace(/[\s，。？、,.?！!]/g, '')));
  let hit = 0;
  for (const c of chars) if (hay.includes(c)) hit++;
  s += (hit / Math.max(chars.length, 1)) * 4;
  return s;
}

function dictScore(q: string, e: DictEntry): number {
  const hay = [e.title, ...e.aliases, e.meaning, e.fixedUsage].join(' ').toLowerCase();
  let s = score(q, hay);
  for (const a of e.aliases) {
    if (q.toLowerCase().includes(a.toLowerCase()) || a.toLowerCase().includes(q.toLowerCase())) s += 6;
  }
  return s;
}

export interface TutorHit {
  dive: ILessonDeepDive;
  lessonId: string;
  score: number;
  dict?: DictEntry;
}

export function searchDives(query: string, top = 3): TutorHit[] {
  const dictHits: TutorHit[] = DICTIONARY.map((e) => ({
    dive: {} as ILessonDeepDive,
    lessonId: '',
    score: dictScore(query, e) + 1, // 字典优先
    dict: e,
  }))
    .filter((h) => h.score >= 3)
    .sort((a, b) => b.score - a.score);

  const diveHits = FLAT.map((f) => ({
    dive: f.dive,
    lessonId: f.lessonId,
    score: score(query, f.haystack),
  }))
    .sort((a, b) => b.score - a.score)
    .filter((h) => h.score >= 3)
    .slice(0, top);

  return [...dictHits, ...diveHits].slice(0, top);
}

export function buildDictionaryAnswer(hit: TutorHit): string {
  if (hit.dict) {
    const e = hit.dict;
    const lines: string[] = [];
    lines.push(`【${e.title}】`);
    lines.push('');
    lines.push('■ 是什么');
    lines.push(e.meaning);
    lines.push('');
    lines.push('■ 固定写法');
    lines.push(e.fixedUsage);
    lines.push('');
    lines.push('■ 哪些部分可以换');
    lines.push(e.variants);
    lines.push('');
    lines.push('■ 常见搭配');
    for (const p of e.patterns) {
      lines.push(`· ${p.name}`);
      lines.push(p.code);
      if (p.note) lines.push(`  说明：${p.note}`);
    }
    lines.push('');
    lines.push('■ 怎么和别的知识拼起来用');
    lines.push(e.combos);
    lines.push('');
    lines.push('■ 在哪些场景会用到');
    lines.push(e.scenarios.map((s) => '· ' + s).join('\n'));
    lines.push('');
    lines.push('■ 新手最容易踩的坑');
    lines.push(e.pitfalls);
    return lines.join('\n');
  }
  const d = hit.dive;
  return [
    `【${d.point}】`,
    '',
    '■ 是什么',
    d.formalDef,
    '',
    '■ 固定写法',
    d.fixed,
    '',
    '■ 哪些部分可以换',
    d.variable,
    '',
    '■ 最小例子',
    ...d.examples.slice(0, 2).flatMap((ex) => [`输入：`, ex.code, '输出：', ex.output, ...(ex.note ? [`说明：${ex.note}`, ''] : [''])]),
    '■ 新手坑',
    d.rookie,
    '',
    '■ 实战用法',
    d.realWorld,
  ].join('\n');
}

export const TUTOR_TIPS = [
  '这个看不懂',
  '怎么用',
  '举个例子',
  '__name__ 是什么',
  '== 和 = 区别',
  '函数怎么写',
] as const;
